# Generated by Django 4.2.24 on 2025-12-23 05:53

from django.db import migrations, models

def remove_duplicate_review_modules(apps, schema_editor):
    PlanModule = apps.get_model('db', 'CaseReviewModule')  # 替换为你的 app 名
    # 只考虑未删除的记录（deleted_at is null）
    qs = PlanModule.objects.filter(deleted_at__isnull=True).order_by('created_at')
    seen = set()
    duplicates = []
    for obj in qs:
        key = (obj.repository_id, obj.name)
        if key in seen:
            # 删除重复项
            obj.delete()  # 或者标记 soft delete：obj.deleted_at = now(); obj.save()
            duplicates.append(key)
        else:
            seen.add(key)
    if duplicates:
        print(f"Removed duplicate ReviewModule entries for keys: {set(duplicates)}")



class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('db', '0154_alter_plancase_result_alter_plancaserecord_result_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_review_modules, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='casereviewmodule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('repository__isnull', False)), fields=('repository', 'name'), name='unique_review_module_repository_name_when_not_deleted'),
        ),
    ]
