# Generated by Django 4.2.24 on 2025-12-25 06:10

from django.db import migrations, models

def truncate_long_names(apps, schema_editor):
    CaseModule = apps.get_model('db', 'CaseModule')
    # 找出所有 name 长度超过 30 的记录并截断
    for obj in CaseModule.objects.all():
        if len(obj.name) > 30:
            print(f"Truncating name: {obj.name} -> {obj.name[:30]}")
            obj.name = obj.name[:30]
            obj.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0155_casereviewmodule_unique_review_module_repository_name_when_not_deleted'),
    ]

    operations = [
        migrations.RunPython(truncate_long_names),
        migrations.AlterField(
            model_name='casemodule',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
