# Generated by Django 4.2.24 on 2025-12-25 06:18

from django.db import migrations, models

def truncate_CaseReviewModule_long_names(apps, schema_editor):
    CaseReviewModule = apps.get_model('db', 'CaseReviewModule')
    # 找出所有 name 长度超过 30 的记录并截断
    for obj in CaseReviewModule.objects.all():
        if len(obj.name) > 30:
            print(f"CaseReviewModule: Truncating name: {obj.name} -> {obj.name[:30]}")
            obj.name = obj.name[:30]
            obj.save(update_fields=['name'])

def truncate_PlanModule_long_names(apps, schema_editor):
    PlanModule = apps.get_model('db', 'PlanModule')
    # 找出所有 name 长度超过 30 的记录并截断
    for obj in PlanModule.objects.all():
        if len(obj.name) > 30:
            print(f"PlanModule: Truncating name: {obj.name} -> {obj.name[:30]}")
            obj.name = obj.name[:30]
            obj.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0156_alter_casemodule_name'),
    ]

    operations = [
        migrations.RunPython(truncate_CaseReviewModule_long_names, truncate_PlanModule_long_names),
        migrations.AlterField(
            model_name='casereviewmodule',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='planmodule',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
