# Generated by Django 4.2.24 on 2025-12-25 06:27

from django.db import migrations, models

def truncate_long_names(apps, schema_editor):
    CaseLabel = apps.get_model('db', 'CaseLabel')
    # 找出所有 name 长度超过 30 的记录并截断
    for obj in CaseLabel.objects.all():
        if len(obj.name) > 30:
            print(f"Truncating name: {obj.name} -> {obj.name[:30]}")
            obj.name = obj.name[:30]
            obj.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0157_alter_casereviewmodule_name_alter_planmodule_name'),
    ]

    operations = [
        migrations.RunPython(truncate_long_names),
        migrations.AlterField(
            model_name='caselabel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
