# Generated by Django 4.2.24 on 2025-12-26 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0158_alter_caselabel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('server_url', models.CharField(max_length=255)),
                ('bind_dn', models.CharField(max_length=255)),
                ('bind_password', models.CharField(max_length=255)),
                ('base_dn', models.CharField(max_length=255)),
                ('user_search_filter', models.CharField(default='(mail=%(user)s)', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'LDAP Configuration',
                'verbose_name_plural': 'LDAP Configurations',
                'db_table': 'ldap_configs',
                'ordering': ('-created_at',),
            },
        ),
    ]
