# Generated by Django 4.2.24 on 2025-12-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0160_milestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='state',
            field=models.CharField(choices=[('未开始', 'gray'), ('进行中', 'blue'), ('延期', 'yellow'), ('已完成', 'green')], default='未开始', verbose_name='Milestone State'),
        ),
    ]
