# Generated by Django 4.2.24 on 2026-01-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0161_milestone_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereviewrecord',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='标记该评审记录是否已被确认', verbose_name='已确认'),
        ),
    ]
