# Generated by Django 4.2.24 on 2026-01-07 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0163_testcase_code_and_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='code',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z0-9]{1,5}-[A-Za-z0-9]{5}$')], verbose_name='TestCase Code'),
        ),
    ]
