# Generated by Django 4.2.24 on 2026-01-07 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0164_alter_testcase_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testcase',
            name='unique_case_repository_name_when_not_deleted',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='code',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z0-9]{1,5}-[A-Za-z0-9]{1,5}$')], verbose_name='TestCase Code'),
        ),
    ]
