# Generated by Django 4.2.24 on 2026-01-08 08:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0165_remove_testcase_unique_case_repository_name_when_not_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='code',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z0-9]{1,5}-[A-Za-z0-9]{1,5}$')], verbose_name='TestCase Code'),
        ),
        migrations.CreateModel(
            name='TestCaseVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('repository_id', models.CharField(max_length=36)),
                ('module_id', models.CharField(blank=True, max_length=36, null=True)),
                ('assignee_id', models.CharField(blank=True, max_length=36, null=True)),
                ('code', models.CharField(blank=True, max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('precondition', models.TextField(blank=True, default='<p></p>')),
                ('steps', models.JSONField(blank=True, default=dict)),
                ('remark', models.TextField(blank=True, default='<p></p>')),
                ('type', models.IntegerField(choices=[(0, '功能测试'), (1, '性能测试'), (2, '安全测试'), (3, '可用性测试'), (4, '兼容性测试'), (5, '回归测试'), (6, '其他')])),
                ('test_type', models.IntegerField(choices=[(0, '手动'), (1, '自动')])),
                ('priority', models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高')])),
                ('state', models.IntegerField(choices=[(0, '待评审'), (1, '已通过'), (2, '已拒绝')], default=0)),
                ('label_ids', models.JSONField(blank=True, default=list)),
                ('issue_ids', models.JSONField(blank=True, default=list)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='db.testcase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'test_case_versions',
                'ordering': ('-created_at',),
                'unique_together': {('case', 'version')},
            },
        ),
    ]
