# Generated by Django 4.2.24 on 2026-01-08 08:43

from django.db import migrations
from django.db.models import Max



def create_from_case(case,TestCaseVersion,TestCase):

    latest = (
        TestCaseVersion.objects.filter(case_id=str(case.id))
        .aggregate(max_version=Max("version"))
        .get("max_version")
    )
    next_version = 0 if latest is None else latest + 1

    label_ids = list(map(str, case.labels.values_list("id", flat=True)))
    issue_ids = list(map(str, case.issues.values_list("id", flat=True)))

    return TestCaseVersion.objects.create(
        case=case,
        version=next_version,
        repository_id=str(case.repository_id),
        module_id=str(case.module_id) if case.module_id else None,
        assignee_id=str(case.assignee_id) if case.assignee_id else None,
        code=case.code or "",
        name=case.name,
        precondition=case.precondition,
        steps=case.steps,
        remark=case.remark,
        type=case.type,
        test_type=case.test_type,
        priority=case.priority,
        state=getattr(case, "state",0),
        label_ids=label_ids,
        issue_ids=issue_ids,
    )


def generate_case_snapshot(apps,schema_editor):
    TestCase = apps.get_model('db', 'TestCase')
    TestCaseVersion = apps.get_model('db', 'TestCaseVersion')


    for case in TestCase.objects.all():
        create_from_case(case=case,TestCaseVersion=TestCaseVersion,TestCase=TestCase)

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0166_alter_testcase_code_testcaseversion'),
    ]

    operations = [
        migrations.RunPython(generate_case_snapshot, reverse_code=migrations.RunPython.noop)
    ]
