# Generated by Django 4.2.24 on 2026-01-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0167_auto_20260108_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='TestCase Code'),
        ),
    ]
