# Generated by Django 4.2.24 on 2026-01-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0168_alter_testcase_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='TestCase Code'),
        ),
    ]
