# Generated by Django 4.2.24 on 2026-01-13 02:54

from django.db import migrations


def add_project(app_model):
    for instance in app_model.objects.all():
        instance.project = instance.repository.project
        instance.save()


def add(apps, schema_editor):
    """给各个模型增加项目"""
    TestPlan = apps.get_model('db', 'TestPlan')
    PlanModule = apps.get_model('db', 'PlanModule')
    CaseReviewModule = apps.get_model('db', 'CaseReviewModule')
    for app_model in [TestPlan, PlanModule, CaseReviewModule]:
        add_project(app_model)


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0170_casereviewmodule_project_planmodule_project_and_more'),
    ]

    operations = [
        migrations.RunPython(add, reverse_code=migrations.RunPython.noop)
    ]
