# Generated by Django 4.2.24 on 2026-01-13 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0171_auto_20260113_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereview',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='db.casereviewmodule', verbose_name='CaseReviewModule'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='db.planmodule', verbose_name='PlanModule'),
        ),
    ]
