# Generated by Django 4.2.24 on 2026-01-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0172_alter_casereview_module_alter_testplan_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereview',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddConstraint(
            model_name='casereview',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('project__isnull', False)), fields=('project', 'name'), name='unique_review_project_name_when_not_deleted'),
        ),
    ]
