# Generated by Django 4.2.24 on 2026-01-13 05:54

from django.db import migrations


def add_project(apps, schema_editor):
    CaseReview = apps.get_model('db', 'CaseReview')
    for instance in CaseReview.objects.all():
        try:
            instance.project = instance.module.repository.project
            instance.save()
        except Exception as e:
            print(e)

class Migration(migrations.Migration):
    dependencies = [
        ('db', '0173_casereview_project_and_more'),
    ]

    operations = [
        migrations.RunPython(add_project, reverse_code=migrations.RunPython.noop)
    ]
