# Generated by Django 4.2.24 on 2026-01-13 06:00

from django.db import migrations


def delete_useless_plane_module(apps, schema_editor):
    PlanModule = apps.get_model('db', 'PlanModule')
    PlanModule.objects.filter(name='未规划计划').delete()


def delete_useless_review_module(apps, schema_editor):
    CaseReviewModule = apps.get_model('db', 'CaseReviewModule')
    CaseReviewModule.objects.filter(name='未规划用例').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0174_auto_20260113_0554'),
    ]

    operations = [
        migrations.RunPython(delete_useless_plane_module, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(delete_useless_review_module, reverse_code=migrations.RunPython.noop)
    ]
