# Generated by Django 4.2.24 on 2026-01-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0175_auto_20260113_0600'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='casereviewmodule',
            name='unique_review_module_repository_name_when_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='planmodule',
            name='unique_plane_module_repository_name_when_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='testplan',
            name='unique_plan_repository_name_when_not_deleted',
        ),
        migrations.RemoveField(
            model_name='casereviewmodule',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='planmodule',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='repository',
        ),
    ]
