# Generated by Django 4.2.24 on 2026-01-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0176_remove_casereviewmodule_unique_review_module_repository_name_when_not_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseversion',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
