# Generated by Django 4.2.24 on 2026-01-15 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0177_alter_testcaseversion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereviewmodule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.casereviewmodule'),
        ),
    ]
