# Generated by Django 4.2.24 on 2026-01-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0179_planmodule_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Step'), (1, 'Text')], default=0),
        ),
        migrations.AddField(
            model_name='testcase',
            name='text_description',
            field=models.TextField(blank=True, default='<p></p>', null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='text_result',
            field=models.TextField(blank=True, default='<p></p>', null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='steps',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='TestCase Steps'),
        ),
    ]
