# Generated by Django 4.2.24 on 2026-01-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0180_testcase_mode_testcase_text_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseversion',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Step'), (1, 'Text')], default=0),
        ),
        migrations.AddField(
            model_name='testcaseversion',
            name='text_description',
            field=models.TextField(blank=True, default='<p></p>', null=True),
        ),
        migrations.AddField(
            model_name='testcaseversion',
            name='text_result',
            field=models.TextField(blank=True, default='<p></p>', null=True),
        ),
    ]
