# Generated by Django 4.2.24 on 2026-01-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0181_testcaseversion_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseversion',
            name='version',
            field=models.FloatField(default=1),
        ),
    ]
