# Generated by Django 4.2.24 on 2026-01-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0182_alter_testcaseversion_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseversion',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Last Modified At'),
        ),
    ]
