# Generated by Django 4.2.24 on 2026-01-27 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0183_alter_testcaseversion_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='plan_assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
