# Generated by Django 4.2.24 on 2026-02-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0185_projectannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='sub_issue',
            field=models.BooleanField(default=False, verbose_name='Sub Issue Flag'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='type',
            field=models.CharField(blank=True, choices=[('未开始', 'Not Started'), ('进行中', 'In Progress'), ('已延期', 'Delayed'), ('已完成', 'Completed'), ('已取消', 'Cancelled')], default='未开始', null=True, verbose_name='TestCase Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cycle_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='intake_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='issue_views_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='module_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='type',
            field=models.IntegerField(choices=[(0, '功能测试'), (1, '性能测试'), (2, '安全测试'), (3, '可用性测试'), (4, '兼容性测试'), (5, '回归测试'), (7, '集成测试'), (99, '其他')], default=0, verbose_name='TestCase Type'),
        ),
        migrations.AlterField(
            model_name='testcaseversion',
            name='type',
            field=models.IntegerField(choices=[(0, '功能测试'), (1, '性能测试'), (2, '安全测试'), (3, '可用性测试'), (4, '兼容性测试'), (5, '回归测试'), (7, '集成测试'), (99, '其他')]),
        ),
    ]
