# Generated by Django 4.2.24 on 2026-02-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0186_cycle_sub_issue_cycle_type_alter_project_cycle_view_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='type',
        ),
        migrations.AddField(
            model_name='cycle',
            name='status',
            field=models.CharField(blank=True, choices=[('未开始', 'Not Started'), ('进行中', 'In Progress'), ('已延期', 'Delayed'), ('已完成', 'Completed'), ('已取消', 'Cancelled')], default='未开始', null=True, verbose_name='TestCase Status'),
        ),
    ]
