# Generated by Django 4.2.24 on 2026-03-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0187_remove_cycle_type_cycle_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='file',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=255, null=True, verbose_name='文件存储路径'),
        ),
        migrations.AddField(
            model_name='file',
            name='storage_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='modules', to='db.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='原始文件名'),
        ),
        migrations.AlterModelTable(
            name='file',
            table='files',
        ),
    ]
