# Generated by Django 4.2.24 on 2026-03-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0188_alter_file_options_file_is_uploaded_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='casemodule',
            name='unique_case_module_repository_name_when_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='casemodule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('repository__isnull', False)), fields=('repository', 'name', 'parent'), name='unique_case_module_repository_name_when_not_deleted'),
        ),
    ]
