# Generated by Django 4.2.24 on 2026-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0189_remove_casemodule_unique_case_module_repository_name_when_not_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='cycles', to='db.file'),
        ),
    ]
