# Generated by Django 4.2.24 on 2026-03-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0190_cycle_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancaserecord',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='plan_case_records', to='db.file'),
        ),
    ]
