# Generated by Django 4.2.24 on 2026-03-11 06:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.issue
import plane.db.models.project
import plane.db.models.user
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0191_plancaserecord_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUserProperty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('filters', models.JSONField(default=plane.db.models.issue.get_default_filters)),
                ('display_filters', models.JSONField(default=plane.db.models.issue.get_default_display_filters)),
                ('display_properties', models.JSONField(default=plane.db.models.issue.get_default_display_properties)),
                ('rich_filters', models.JSONField(default=dict)),
                ('preferences', models.JSONField(default=plane.db.models.project.get_default_preferences)),
                ('sort_order', models.FloatField(default=65535)),
            ],
            options={
                'verbose_name': 'Project User Property',
                'verbose_name_plural': 'Project User Properties',
                'db_table': 'project_user_properties',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RenameField(
            model_name='draftissue',
            old_name='description',
            new_name='description_json',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='description',
            new_name='description_json',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='description',
            new_name='description_json',
        ),
        migrations.AddField(
            model_name='apitoken',
            name='allowed_rate_limit',
            field=models.CharField(default='60/min', max_length=255),
        ),
        migrations.AddField(
            model_name='issueview',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_navigation_tour_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_subscribed_to_changelog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_view_mode',
            field=models.CharField(choices=[('full', 'Full'), ('compact', 'Compact')], default='full', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='product_tour',
            field=models.JSONField(default=plane.db.models.user.get_default_product_tour),
        ),
        migrations.AddField(
            model_name='user',
            name='is_password_reset_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhook',
            name='version',
            field=models.CharField(default='v1', max_length=50),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='explored_features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='getting_started_checklist',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='tips',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='estimatepoint',
            name='key',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='IssueUserProperty',
        ),
        migrations.AddField(
            model_name='projectuserproperty',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='projectuserproperty',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='projectuserproperty',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='projectuserproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_property_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectuserproperty',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='projectuserproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'project'), name='project_user_property_unique_user_project_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='projectuserproperty',
            unique_together={('user', 'project', 'deleted_at')},
        ),
    ]
