# Generated by Django 4.2.24 on 2026-03-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0192_projectuserproperty_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='casereview',
            name='unique_review_project_name_when_not_deleted',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='type',
            field=models.IntegerField(choices=[(0, '功能测试'), (1, '性能测试'), (2, '安全测试'), (4, '兼容测试'), (5, '回归测试'), (7, '集成测试'), (99, '其他')], default=0, verbose_name='TestCase Type'),
        ),
        migrations.AlterField(
            model_name='testcaseversion',
            name='type',
            field=models.IntegerField(choices=[(0, '功能测试'), (1, '性能测试'), (2, '安全测试'), (4, '兼容测试'), (5, '回归测试'), (7, '集成测试'), (99, '其他')]),
        ),
        migrations.AddConstraint(
            model_name='casereview',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('module__isnull', False), ('project__isnull', False)), fields=('project', 'module', 'name'), name='unique_review_project_module_name_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='casereview',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('module__isnull', True), ('project__isnull', False)), fields=('project', 'name'), name='unique_review_project_name_when_module_null_not_deleted'),
        ),
    ]
