# Generated by Django 4.2.24 on 2026-03-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0193_update_case_review_unique_constraint_with_module'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='state',
            name='state_unique_name_project_when_deleted_at_null',
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='state',
            name='issue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='db.issuetype'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('name', 'issue_type', 'project', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'issue_type', 'project'), name='state_unique_name_project_when_deleted_at_null'),
        ),
    ]
