# Generated by Django 4.2.24 on 2026-03-16 06:39

from django.db import migrations


def copy_state(apps, schema_editor):
    """将现有的状态（issue_type 为空）复制成多份，每份关联到一种 issue_type"""
    State = apps.get_model('db', 'State')
    Project = apps.get_model('db', 'Project')
    ProjectIssueType = apps.get_model('db', 'ProjectIssueType')

    for project in Project.objects.all():
        # 获取该项目的原始状态（issue_type 为空的，即迁移前的状态）
        original_states = State.objects.filter(project=project, issue_type__isnull=True)
        project_issue_types = ProjectIssueType.objects.filter(project=project)

        for project_issue_type in project_issue_types:
            issue_type = project_issue_type.issue_type
            for state in original_states:
                # 创建副本，设置对应的 issue_type
                State.objects.create(
                    project=project,
                    workspace=project.workspace,
                    issue_type=issue_type,
                    name=state.name,
                    description=state.description,
                    color=state.color,
                    slug=state.slug,
                    sequence=state.sequence,
                    group=state.group,
                    is_triage=state.is_triage,
                    default=state.default,
                    external_source=state.external_source,
                    external_id=state.external_id,
                )


def reverse_copy_state(apps, schema_editor):
    """回滚：删除通过 copy_state 创建的状态（issue_type 不为空的状态）"""
    State = apps.get_model('db', 'State')
    State.objects.filter(issue_type__isnull=False).delete(soft=False)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0194_remove_state_state_unique_name_project_when_deleted_at_null_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_state, reverse_copy_state),
    ]
