# Generated by Django 4.2.24 on 2026-03-17 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0195_auto_20260316_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='工作流名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='db.issuetype', verbose_name='工作项类型')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'workflows',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('approval_type', models.CharField(choices=[('any', '任一人通过'), ('all', '全部通过'), ('n_of_m', '至少 N 人通过')], default='any', max_length=10, verbose_name='审批通过规则')),
                ('required_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最少通过人数（仅 n_of_m 模式生效）')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='db.state', verbose_name='起始状态（为空表示初始流转）')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='db.state', verbose_name='目标状态')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='db.workflow', verbose_name='所属工作流')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workflow Transition',
                'verbose_name_plural': 'Workflow Transitions',
                'db_table': 'workflow_transitions',
                'ordering': ('workflow', 'from_state'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransitionApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='db.workflowtransition', verbose_name='所属流转边')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Workflow Transition Approval',
                'verbose_name_plural': 'Workflow Transition Approvals',
                'db_table': 'workflow_transition_approvals',
                'ordering': ('transition', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='IssueTransitionRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='审批状态')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_records_as_source', to='db.state', verbose_name='起始状态')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_records', to='db.issue', verbose_name='工单')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('to_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_records_as_target', to='db.state', verbose_name='目标状态')),
                ('transition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_transition_records', to='db.workflowtransition', verbose_name='触发的流转边')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Transition Record',
                'verbose_name_plural': 'Issue Transition Records',
                'db_table': 'issue_transition_records',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IssueTransitionApprovalRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(blank=True, choices=[('approved', '通过'), ('rejected', '拒绝')], max_length=20, null=True, verbose_name='审批操作（null 表示尚未操作）')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_approval_records', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('transition_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='db.issuetransitionrecord', verbose_name='所属流转申请')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Issue Transition Approval Record',
                'verbose_name_plural': 'Issue Transition Approval Records',
                'db_table': 'issue_transition_approval_records',
                'ordering': ('transition_record', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='workflowtransitionapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('transition', 'approver'), name='workflow_approval_unique_transition_approver_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workflow', 'from_state', 'to_state'), name='workflow_transition_unique_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('approval_type', 'n_of_m'), _negated=True), ('required_count__isnull', False), _connector='OR'), name='workflow_transition_required_count_set_when_n_of_m'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.CheckConstraint(check=models.Q(('approval_type', 'n_of_m'), ('required_count__isnull', True), _connector='OR'), name='workflow_transition_required_count_null_when_not_n_of_m'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('project', 'issue_type'), name='workflow_unique_active_per_project_issue_type'),
        ),
        migrations.AddIndex(
            model_name='issuetransitionrecord',
            index=models.Index(fields=['issue', 'status'], name='idx_issue_trans_status'),
        ),
        migrations.AddConstraint(
            model_name='issuetransitionapprovalrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('transition_record', 'approver'), name='issue_approval_record_unique_record_approver_when_not_deleted'),
        ),
    ]
