# Generated by Django 4.2.24 on 2026-03-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0196_workflow_workflowtransition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, verbose_name='工作流描述'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
    ]
