# Generated by Django 4.2.24 on 2026-03-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0197_workflow_description_alter_workflow_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetransitionapprovalrecord',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='审批意见'),
        ),
    ]
