# Generated by Django 4.2.24 on 2026-03-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0201_create_default_bug_workflow_for_existing_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPmsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_project', models.CharField(max_length=255, verbose_name='子项目名称')),
                ('project_code', models.CharField(max_length=255, verbose_name='项目编号')),
                ('meter_type', models.CharField(max_length=255, verbose_name='产品类型')),
                ('software_version', models.CharField(max_length=255, verbose_name='软件版本')),
                ('tool_version', models.CharField(max_length=255, verbose_name='工具软件版本')),
                ('reproduce', models.CharField(max_length=255, verbose_name='易现等级1')),
                ('issue_ids', models.JSONField(default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_pms_info', to='db.project')),
            ],
            options={
                'db_table': 'project_pms_info',
            },
        ),
    ]
