# Generated by Django 4.2.24 on 2026-03-23 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0202_projectpmsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_groups', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Group',
                'verbose_name_plural': 'Workspace Groups',
                'db_table': 'workspace_groups',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_roles', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Role',
                'verbose_name_plural': 'Workspace Roles',
                'db_table': 'workspace_roles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceGroupRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to='db.workspacegroup')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_groups', to='db.workspacerole')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Workspace Group Role',
                'verbose_name_plural': 'Workspace Group Roles',
                'db_table': 'workspace_group_roles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceGroupMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='db.workspacegroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_groups', to='db.workspacemember')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Workspace Group Member',
                'verbose_name_plural': 'Workspace Group Members',
                'db_table': 'workspace_group_members',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_project_roles', to='db.workspacerole')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Project Role',
                'verbose_name_plural': 'Project Roles',
                'db_table': 'project_roles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectMemberRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='db.projectmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_member_entries', to='db.projectrole')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Project Member Role',
                'verbose_name_plural': 'Project Member Roles',
                'db_table': 'project_member_roles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectGroupRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_group_roles', to='db.workspacegroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_role_entries', to='db.projectrole')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Project Group Role',
                'verbose_name_plural': 'Project Group Roles',
                'db_table': 'project_group_roles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='projectmember',
            name='custom_roles',
            field=models.ManyToManyField(blank=True, related_name='role_members', through='db.ProjectMemberRole', to='db.projectrole'),
        ),
        migrations.AddConstraint(
            model_name='workspacerole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='workspace_role_unique_workspace_name_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacerole',
            unique_together={('workspace', 'name', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='workspacegrouprole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('group', 'role'), name='workspace_group_role_unique_group_role_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacegrouprole',
            unique_together={('group', 'role', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='workspacegroupmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('group', 'member'), name='workspace_group_member_unique_group_member_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacegroupmember',
            unique_together={('group', 'member', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='workspacegroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='workspace_group_unique_workspace_name_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacegroup',
            unique_together={('workspace', 'name', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='projectrole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'name'), name='project_role_unique_project_name_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together={('project', 'name', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='projectmemberrole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('member', 'role'), name='project_member_role_unique_member_role_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmemberrole',
            unique_together={('member', 'role', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='projectgrouprole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('group', 'role'), name='project_group_role_unique_group_role_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='projectgrouprole',
            unique_together={('group', 'role', 'deleted_at')},
        ),
    ]
