# Generated by Django 4.2.24 on 2026-04-07 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0207_seed_default_project_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='scope',
            field=models.CharField(choices=[('workspace', '工作区'), ('project', '项目')], default='workspace', max_length=20),
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(verbose_name='工时日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='花费小时数')),
                ('description', models.TextField(blank=True, verbose_name='工作描述')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='db.issue', verbose_name='所属工作项')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL, verbose_name='工时人员')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='db.project', verbose_name='所属项目')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='db.testcase', verbose_name='所属测试用例')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': '工时记录',
                'verbose_name_plural': '工时记录',
                'db_table': 'timesheets',
                'ordering': ('-date', '-start_time'),
                'indexes': [models.Index(fields=['member', 'date'], name='idx_timesheet_member_date'), models.Index(fields=['project'], name='idx_timesheet_project'), models.Index(fields=['issue'], name='idx_timesheet_issue'), models.Index(fields=['test_case'], name='idx_timesheet_test_case')],
            },
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('issue__isnull', True), ('test_case__isnull', True), _connector='OR'), name='timesheet_issue_and_test_case_not_both_set'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(check=models.Q(('hours__gt', 0)), name='timesheet_hours_positive'),
        ),
    ]
