# Generated by Django 4.2.24 on 2026-04-09 08:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0209_add_timesheet_duplicate_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Total estimated working hours for this project (default: 100h)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Estimated Hours'),
        ),
    ]
