# Generated by Django 4.2.24 on 2026-04-10 06:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import plane.db.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0210_project_estimated_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Total estimated working hours for this project (default: 100h)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), plane.db.models.project.validate_estimated_hours_half_step], verbose_name='Estimated Hours'),
        ),
    ]
