# Generated by Django 4.2.24 on 2026-04-11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

import plane.db.models.release


def copy_modules_to_releases(apps, schema_editor):
    from django.db import connection

    with connection.cursor() as cursor:
        # 1. Copy modules -> releases
        cursor.execute("""
            INSERT INTO releases (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                name, description, note, description_text, description_html,
                start_date, target_date, status, lead_id,
                view_props, sort_order, external_source, external_id,
                archived_at, logo_props
            )
            SELECT
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                name, description, note, description_text, description_html,
                start_date, target_date, status, lead_id,
                view_props, sort_order, external_source, external_id,
                archived_at, logo_props
            FROM modules
        """)

        # 2. Copy module_issues -> release_issues
        cursor.execute("""
            INSERT INTO release_issues (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                release_id, issue_id
            )
            SELECT
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                module_id, issue_id
            FROM module_issues
        """)

        # 3. Copy module_members -> release_members
        cursor.execute("""
            INSERT INTO release_members (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                release_id, member_id
            )
            SELECT
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                module_id, member_id
            FROM module_members
        """)

        # 4. Copy module_links -> release_links
        cursor.execute("""
            INSERT INTO release_links (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                title, url, release_id, metadata
            )
            SELECT
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                title, url, module_id, metadata
            FROM module_links
        """)

        # 5. Copy module_user_properties -> release_user_properties
        cursor.execute("""
            INSERT INTO release_user_properties (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                release_id, user_id,
                filters, display_filters, display_properties, rich_filters
            )
            SELECT
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                module_id, user_id,
                filters, display_filters, display_properties, rich_filters
            FROM module_user_properties
        """)

        # 6. Copy draft_issue_modules -> draft_issue_releases
        cursor.execute("""
            INSERT INTO draft_issue_releases (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                workspace_id, project_id,
                release_id, draft_issue_id
            )
            SELECT
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                workspace_id, project_id,
                module_id, draft_issue_id
            FROM draft_issue_modules
        """)

        # 7. For each Cycle that has a module_id, set release_id to the same value
        cursor.execute("""
            UPDATE cycles
            SET release_id = module_id
            WHERE module_id IS NOT NULL
        """)

        # 8. Copy M2M entries from plan_modules_relations to plan_releases_relations
        cursor.execute("""
            INSERT INTO plan_releases_relations (id, testplan_id, release_id)
            SELECT id, testplan_id, module_id
            FROM plan_modules_relations
        """)

        # 9. Migrate user favorites: module -> release
        cursor.execute("""
            INSERT INTO user_favorites (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                user_id, entity_type, entity_identifier, name, is_folder, sequence,
                project_id, parent_id, workspace_id
            )
            SELECT
                gen_random_uuid(), created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                user_id, 'release', entity_identifier, name, is_folder, sequence,
                project_id, parent_id, workspace_id
            FROM user_favorites
            WHERE entity_type = 'module'
        """)

        # 10. Migrate user recent visits: module -> release
        cursor.execute("""
            INSERT INTO user_recent_visits (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                workspace_id, user_id, entity_identifier, entity_name, project_id,
                visited_at
            )
            SELECT
                gen_random_uuid(), created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                workspace_id, user_id, entity_identifier, 'release', project_id,
                visited_at
            FROM user_recent_visits
            WHERE entity_name = 'module'
        """)

        # 11. Migrate issue activities: field "modules" -> duplicate as "releases"
        cursor.execute("""
            INSERT INTO issue_activities (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                issue_id, issue_comment_id, actor_id, verb, field,
                old_value, new_value, comment, attachments,
                old_identifier, new_identifier, epoch
            )
            SELECT
                gen_random_uuid(), created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                issue_id, issue_comment_id, actor_id, verb, 'releases',
                old_value, new_value,
                REPLACE(comment, 'module', 'release'), attachments,
                old_identifier, new_identifier, epoch
            FROM issue_activities
            WHERE field = 'modules'
        """)

        # 12. Preserve historical issue-version semantics before Module is reused upstream.
        # The modules UUIDs here now represent migrated releases with the same ids.
        cursor.execute("""
            UPDATE issue_versions
            SET meta = jsonb_set(
                jsonb_set(
                    COALESCE(meta, '{}'::jsonb),
                    '{legacy_module_ids}',
                    to_jsonb(modules),
                    true
                ),
                '{release_ids}',
                to_jsonb(modules),
                true
            )
            WHERE COALESCE(array_length(modules, 1), 0) > 0
        """)

        # 13. Copy Module files M2M to Release files M2M
        cursor.execute("""
            INSERT INTO releases_files (release_id, file_id)
            SELECT module_id, file_id
            FROM modules_files
        """)

        # 14. Clean up Module original data (data has been migrated to Release)
        cursor.execute("DELETE FROM modules_files")
        cursor.execute("DELETE FROM issue_activities WHERE field = 'modules'")
        cursor.execute("DELETE FROM user_recent_visits WHERE entity_name = 'module'")
        cursor.execute("DELETE FROM user_favorites WHERE entity_type = 'module'")
        cursor.execute("DELETE FROM plan_modules_relations")
        cursor.execute("UPDATE cycles SET module_id = NULL")
        cursor.execute("DELETE FROM draft_issue_modules")
        cursor.execute("DELETE FROM module_user_properties")
        cursor.execute("DELETE FROM module_links")
        cursor.execute("DELETE FROM module_members")
        cursor.execute("DELETE FROM module_issues")
        cursor.execute("DELETE FROM modules")


def reverse_copy(apps, schema_editor):
    from django.db import connection

    with connection.cursor() as cursor:
        # 1. Restore Module data from Release
        cursor.execute("""
            INSERT INTO modules (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                name, description, note, description_text, description_html,
                start_date, target_date, status, lead_id,
                view_props, sort_order, external_source, external_id,
                archived_at, logo_props
            )
            SELECT
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                name, description, note, description_text, description_html,
                start_date, target_date, status, lead_id,
                view_props, sort_order, external_source, external_id,
                archived_at, logo_props
            FROM releases
        """)
        cursor.execute("""
            INSERT INTO module_issues (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id, module_id, issue_id
            )
            SELECT
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id, release_id, issue_id
            FROM release_issues
        """)
        cursor.execute("""
            INSERT INTO module_members (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id, module_id, member_id
            )
            SELECT
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id, release_id, member_id
            FROM release_members
        """)
        cursor.execute("""
            INSERT INTO module_links (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id, title, url, module_id, metadata
            )
            SELECT
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id, title, url, release_id, metadata
            FROM release_links
        """)
        cursor.execute("""
            INSERT INTO module_user_properties (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id, module_id, user_id,
                filters, display_filters, display_properties, rich_filters
            )
            SELECT
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id, release_id, user_id,
                filters, display_filters, display_properties, rich_filters
            FROM release_user_properties
        """)
        cursor.execute("""
            INSERT INTO draft_issue_modules (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                workspace_id, project_id, module_id, draft_issue_id
            )
            SELECT
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                workspace_id, project_id, release_id, draft_issue_id
            FROM draft_issue_releases
        """)
        cursor.execute("""
            UPDATE cycles SET module_id = release_id WHERE release_id IS NOT NULL
        """)
        cursor.execute("""
            INSERT INTO plan_modules_relations (id, testplan_id, module_id)
            SELECT id, testplan_id, release_id FROM plan_releases_relations
        """)
        cursor.execute("""
            INSERT INTO modules_files (module_id, file_id)
            SELECT release_id, file_id FROM releases_files
        """)
        cursor.execute("""
            INSERT INTO user_favorites (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                user_id, entity_type, entity_identifier, name, is_folder, sequence,
                project_id, parent_id, workspace_id
            )
            SELECT
                gen_random_uuid(), created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                user_id, 'module', entity_identifier, name, is_folder, sequence,
                project_id, parent_id, workspace_id
            FROM user_favorites
            WHERE entity_type = 'release'
        """)
        cursor.execute("""
            INSERT INTO user_recent_visits (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                workspace_id, user_id, entity_identifier, entity_name, project_id, visited_at
            )
            SELECT
                gen_random_uuid(), created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                workspace_id, user_id, entity_identifier, 'module', project_id, visited_at
            FROM user_recent_visits
            WHERE entity_name = 'release'
        """)
        cursor.execute("""
            INSERT INTO issue_activities (
                id, created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                issue_id, issue_comment_id, actor_id, verb, field,
                old_value, new_value, comment, attachments,
                old_identifier, new_identifier, epoch
            )
            SELECT
                gen_random_uuid(), created_at, updated_at, created_by_id, updated_by_id, deleted_at,
                project_id, workspace_id,
                issue_id, issue_comment_id, actor_id, verb, 'modules',
                old_value, new_value,
                REPLACE(comment, 'release', 'module'), attachments,
                old_identifier, new_identifier, epoch
            FROM issue_activities
            WHERE field = 'releases'
        """)

        cursor.execute("""
            UPDATE issue_versions
            SET meta = COALESCE(meta, '{}'::jsonb) - 'release_ids' - 'legacy_module_ids'
            WHERE COALESCE(meta, '{}'::jsonb) ? 'release_ids'
               OR COALESCE(meta, '{}'::jsonb) ? 'legacy_module_ids'
        """)

        # 2. Clean up Release data
        cursor.execute("DELETE FROM releases_files")
        cursor.execute("DELETE FROM issue_activities WHERE field = 'releases'")
        cursor.execute("DELETE FROM user_recent_visits WHERE entity_name = 'release'")
        cursor.execute("DELETE FROM user_favorites WHERE entity_type = 'release'")
        cursor.execute("DELETE FROM plan_releases_relations")
        cursor.execute("UPDATE cycles SET release_id = NULL")
        cursor.execute("DELETE FROM draft_issue_releases")
        cursor.execute("DELETE FROM release_user_properties")
        cursor.execute("DELETE FROM release_links")
        cursor.execute("DELETE FROM release_members")
        cursor.execute("DELETE FROM release_issues")
        cursor.execute("DELETE FROM releases")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("db", "0211_alter_project_estimated_hours"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── 1. Create Release table ──────────────────────────────────────
        migrations.CreateModel(
            name="Release",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=255, verbose_name="Release Name")),
                ("description", models.TextField(blank=True, verbose_name="Release Description")),
                ("note", models.TextField(blank=True, null=True, verbose_name="Release Note")),
                ("description_text", models.JSONField(blank=True, null=True, verbose_name="Release Description RT")),
                ("description_html", models.JSONField(blank=True, null=True, verbose_name="Release Description HTML")),
                ("start_date", models.DateField(null=True)),
                ("target_date", models.DateField(null=True)),
                ("status", models.CharField(
                    choices=[
                        ("backlog", "Backlog"),
                        ("planned", "Planned"),
                        ("in-progress", "In Progress"),
                        ("paused", "Paused"),
                        ("completed", "Completed"),
                        ("cancelled", "Cancelled"),
                    ],
                    default="planned",
                    max_length=20,
                )),
                ("view_props", models.JSONField(default=dict)),
                ("sort_order", models.FloatField(default=65535)),
                ("external_source", models.CharField(blank=True, max_length=255, null=True)),
                ("external_id", models.CharField(blank=True, max_length=255, null=True)),
                ("archived_at", models.DateTimeField(null=True)),
                ("logo_props", models.JSONField(default=dict)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
                ("lead", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="release_leads", to=settings.AUTH_USER_MODEL)),
                ("files", models.ManyToManyField(blank=True, related_name="releases", to="db.file")),
            ],
            options={
                "verbose_name": "Release",
                "verbose_name_plural": "Releases",
                "db_table": "releases",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="release",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("name", "project"),
                name="release_unique_name_project_when_deleted_at_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="release",
            unique_together={("name", "project", "deleted_at")},
        ),

        # ── 2. Create ReleaseMember table ────────────────────────────────
        migrations.CreateModel(
            name="ReleaseMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
                ("release", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="db.release")),
                ("member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Release Member",
                "verbose_name_plural": "Release Members",
                "db_table": "release_members",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="releasemember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("release", "member"),
                name="release_member_unique_release_member_when_deleted_at_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="releasemember",
            unique_together={("release", "member", "deleted_at")},
        ),

        # ── Add members M2M through field on Release ─────────────────────
        migrations.AddField(
            model_name="release",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="release_members",
                through="db.ReleaseMember",
                through_fields=("release", "member"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        # ── 3. Create ReleaseIssue table ─────────────────────────────────
        migrations.CreateModel(
            name="ReleaseIssue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
                ("release", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="issue_release", to="db.release")),
                ("issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="issue_release", to="db.issue")),
            ],
            options={
                "verbose_name": "Release Issue",
                "verbose_name_plural": "Release Issues",
                "db_table": "release_issues",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="releaseissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issue", "release"),
                name="release_issue_unique_issue_release_when_deleted_at_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="releaseissue",
            unique_together={("issue", "release", "deleted_at")},
        ),

        # ── 4. Create ReleaseLink table ──────────────────────────────────
        migrations.CreateModel(
            name="ReleaseLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
                ("release", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="link_release", to="db.release")),
            ],
            options={
                "verbose_name": "Release Link",
                "verbose_name_plural": "Release Links",
                "db_table": "release_links",
                "ordering": ("-created_at",),
            },
        ),

        # ── 5. Create ReleaseUserProperties table ────────────────────────
        migrations.CreateModel(
            name="ReleaseUserProperties",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("filters", models.JSONField(default=plane.db.models.release.get_default_filters)),
                ("display_filters", models.JSONField(default=plane.db.models.release.get_default_display_filters)),
                ("display_properties", models.JSONField(default=plane.db.models.release.get_default_display_properties)),
                ("rich_filters", models.JSONField(default=dict)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
                ("release", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="release_user_properties", to="db.release")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="release_user_properties", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Release User Property",
                "verbose_name_plural": "Release User Properties",
                "db_table": "release_user_properties",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="releaseuserproperties",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("release", "user"),
                name="release_user_properties_unique_release_user_when_deleted_at_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="releaseuserproperties",
            unique_together={("release", "user", "deleted_at")},
        ),

        # ── 6. Create DraftIssueRelease table ────────────────────────────
        migrations.CreateModel(
            name="DraftIssueRelease",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
                ("project", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("release", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="draft_issue_release", to="db.release")),
                ("draft_issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="draft_issue_release", to="db.draftissue")),
            ],
            options={
                "verbose_name": "Draft Issue Release",
                "verbose_name_plural": "Draft Issue Releases",
                "db_table": "draft_issue_releases",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="draftissuerelease",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("draft_issue", "release"),
                name="release_draft_issue_unique_issue_release_when_deleted_at_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="draftissuerelease",
            unique_together={("draft_issue", "release", "deleted_at")},
        ),

        # ── 7. Add release FK to Cycle ───────────────────────────────────
        migrations.AddField(
            model_name="cycle",
            name="release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="release_cycles",
                to="db.release",
            ),
        ),

        # ── 8. Add releases M2M to TestPlan ──────────────────────────────
        migrations.AddField(
            model_name="testplan",
            name="releases",
            field=models.ManyToManyField(
                blank=True,
                db_table="plan_releases_relations",
                related_name="plans",
                to="db.release",
            ),
        ),

        # ── 9. Data migration: copy Module data to Release ───────────────
        migrations.RunPython(
            copy_modules_to_releases,
            reverse_code=reverse_copy,
            atomic=True,
        ),

        # ── 10. Remove custom fields from Module (restored to upstream) ──
        migrations.RemoveField(
            model_name="module",
            name="note",
        ),
        migrations.RemoveField(
            model_name="module",
            name="files",
        ),   ]
