# Generated by Django 4.2.24 on 2026-04-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0213_seed_module_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grade',
            field=models.CharField(blank=True, choices=[('P+', 'P+'), ('P', 'P'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=4, null=True, verbose_name='Project Grade'),
        ),
    ]
