# Generated by Django 4.2.24 on 2026-04-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0216_backfill_legacy_project_grade_to_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pms_project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
