# Generated by Cursor

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0221_project_scoped_issue_types"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IssuePropertyValue",
        ),
        migrations.DeleteModel(
            name="IssueTypeProperty",
        ),
        migrations.DeleteModel(
            name="ProjectIssueType",
        ),
    ]
