# Generated by Django 4.2.24 on 2026-04-29 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0222_delete_issue_type_legacy_dynamic_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExtraField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo_props', models.JSONField(default=dict)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('user', 'User')], default='text', max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.FloatField(default=65535)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='db.issuetype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Type Extra Field',
                'verbose_name_plural': 'Type Extra Fields',
                'db_table': 'type_extra_fields',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TypeExtraFieldValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('extra_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='db.typeextrafield')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_extra_field_values', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Type Extra Field Value',
                'verbose_name_plural': 'Type Extra Field Values',
                'db_table': 'type_extra_field_values',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='typeextrafieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'extra_field'), name='type_extra_field_value_unique_active'),
        ),
        migrations.AddConstraint(
            model_name='typeextrafield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'issue_type', 'key'), name='type_extra_field_unique_key_active'),
        ),
    ]
