# Generated by Django 4.2.24 on 2026-05-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0224_typeextrafield_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='typeextrafield',
            name='type_extra_field_unique_key_active',
        ),
        migrations.RemoveField(
            model_name='typeextrafield',
            name='key',
        ),
    ]
