# Generated by Django 4.2.24 on 2026-05-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0225_remove_typeextrafield_type_extra_field_unique_key_active_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='typeextrafield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'issue_type', 'name'), name='type_extra_field_unique_name_active'),
        ),
    ]
