# Generated by Django 4.2.24 on 2026-05-09 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0228_seed_issue_type_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTransitionRequiredField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('extra_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_in_transitions', to='db.typeextrafield', verbose_name='所属字段')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_fields', to='db.workflowtransition', verbose_name='所属工作流')),
            ],
            options={
                'db_table': 'workflow_transition_required_fields',
            },
        ),
        migrations.AddConstraint(
            model_name='workflowtransitionrequiredfield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workflow', 'extra_field'), name='workflow_transition_required_field_unique_when_not_deleted'),
        ),
    ]
