# Generated by Django 4.2.24 on 2026-05-12 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0229_workflowtransitionrequiredfield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'db_table': 'issue_type_category',
            },
        ),
        migrations.AddField(
            model_name='issuetype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_types', to='db.issuetypecategory'),
        ),
        migrations.AddConstraint(
            model_name='issuetypecategory',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='issue_type_category_unique_name'),
        ),
    ]
