# Generated by Django 4.2.24 on 2026-05-15 08:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


# 数据迁移交由 `manage.py migrate_asset_paths` 命令完成（支持 dry-run / 续跑），
# 这里只负责 schema 建表与索引，避免在 schema 迁移阶段长时间持锁。


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0234_fileasset_unify_paths"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilePath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("WORKSPACE", "Workspace"),
                            ("PROJECT", "Project"),
                            ("ISSUE", "Issue"),
                            ("DRAFT_ISSUE", "Draft Issue"),
                            ("PAGE", "Page"),
                            ("TESTCASE", "Testcase"),
                            ("CYCLE", "Cycle"),
                            ("RELEASE", "Release"),
                            ("PLAN_CASE_RECORD", "Plan Case Record"),
                            ("USER_ROOT", "User Root"),
                            ("USER", "User"),
                            ("ISSUES_CATEGORY", "Issues Category"),
                            ("DRAFTS_CATEGORY", "Drafts Category"),
                            ("PAGES_CATEGORY", "Pages Category"),
                            ("CYCLES_CATEGORY", "Cycles Category"),
                            ("RELEASES_CATEGORY", "Releases Category"),
                            ("CASES_CATEGORY", "Cases Category"),
                            ("PLAN_CASE_RECORDS_CATEGORY", "Plan Case Records Category"),
                            ("TEMP_CATEGORY", "Temp Category"),
                            ("TEMP", "Temp"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.CharField(blank=True, max_length=64, null=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="db.filepath",
                    ),
                ),
            ],
            options={
                "db_table": "filepath",
            },
        ),
        migrations.AddField(
            model_name="fileasset",
            name="path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="db.filepath",
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="filename",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="filepath",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("entity_id__isnull", False), ("parent__isnull", True)
                ),
                fields=("entity_type", "entity_id"),
                name="filepath_uniq_root_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="filepath",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("entity_id__isnull", True), ("parent__isnull", True)
                ),
                fields=("entity_type",),
                name="filepath_uniq_root_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="filepath",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "entity_type", "entity_id"),
                name="filepath_uniq_child",
            ),
        ),
    ]
