# Generated by Django 4.2.24 on 2026-05-20 03:33

from django.db import migrations
from django.db.models import Min


TARGET_WORKSPACE_SLUG = "kfcd"
APPROVER_DISPLAY_NAMES = ["欧秋洁", "何洽", "钟长会"]
DEFECT_TYPE_NAMES = {"缺陷", "Bug", "bug", "Defect", "defect"}
MEMBER_ROLE = 15


def _is_defect_issue_type(issue_type):
    category = getattr(issue_type, "category", None)
    if category is not None and getattr(category, "name", None) == "缺陷":
        return True
    return issue_type.name in DEFECT_TYPE_NAMES


def _add_users_to_project(ProjectUserProperty, ProjectMember, users, project):
    user_ids = [user.id for user in users]
    if not user_ids:
        return

    member_sort_orders = (
        ProjectUserProperty.objects.filter(
            workspace_id=project.workspace_id,
            user_id__in=user_ids,
            deleted_at__isnull=True,
        )
        .values("user_id")
        .annotate(min_sort_order=Min("sort_order"))
    )
    sort_order_map = {
        str(item["user_id"]): item["min_sort_order"] for item in member_sort_orders
    }

    project_members = []
    user_properties = []
    for user in users:
        min_sort_order = sort_order_map.get(str(user.id))
        project_members.append(
            ProjectMember(
                member_id=user.id,
                role=MEMBER_ROLE,
                project_id=project.id,
                workspace_id=project.workspace_id,
            )
        )
        user_properties.append(
            ProjectUserProperty(
                user_id=user.id,
                project_id=project.id,
                workspace_id=project.workspace_id,
                sort_order=(
                    min_sort_order - 10000 if min_sort_order is not None else 65535
                ),
            )
        )

    ProjectMember.objects.bulk_create(
        project_members, batch_size=10, ignore_conflicts=True
    )
    ProjectUserProperty.objects.bulk_create(
        user_properties, batch_size=10, ignore_conflicts=True
    )


def _ensure_default_reject_approvers(
    Workflow,
    WorkflowTransition,
    WorkflowTransitionApproval,
    State,
    project,
    defect_issue_type,
    approver_users,
):
    workflow = Workflow.objects.filter(
        project=project,
        issue_type=defect_issue_type,
        is_active=True,
        deleted_at__isnull=True,
    ).first()
    if workflow is None:
        return

    states = State.objects.filter(
        project=project,
        issue_type=defect_issue_type,
        name__in=["Pending-Reject", "Rejected"],
        deleted_at__isnull=True,
    )
    state_map = {state.name: state for state in states}
    from_state = state_map.get("Pending-Reject")
    to_state = state_map.get("Rejected")
    if from_state is None or to_state is None:
        return

    transition = WorkflowTransition.objects.filter(
        workflow=workflow,
        from_state=from_state,
        to_state=to_state,
        deleted_at__isnull=True,
    ).first()
    if transition is None:
        transition = WorkflowTransition.objects.create(
            workflow=workflow,
            from_state=from_state,
            to_state=to_state,
            project_id=project.id,
            workspace_id=project.workspace_id,
            approval_type="any",
            required_count=None,
            dynamic_approver_types=[],
        )

    if transition.approval_type != "any" or transition.required_count is not None:
        transition.approval_type = "any"
        transition.required_count = None
        transition.save(update_fields=["approval_type", "required_count", "updated_at"])

    existing_approver_ids = set(
        WorkflowTransitionApproval.objects.filter(
            transition_id=transition.id,
            deleted_at__isnull=True,
        ).values_list("approver_id", flat=True)
    )
    to_create = [
        WorkflowTransitionApproval(transition_id=transition.id, approver_id=user.id)
        for user in approver_users
        if user.id not in existing_approver_ids
    ]
    if to_create:
        WorkflowTransitionApproval.objects.bulk_create(to_create, ignore_conflicts=True)


def main(apps, schema_editor):
    Project = apps.get_model("db", "Project")
    ProjectUserProperty = apps.get_model("db", "ProjectUserProperty")
    ProjectMember = apps.get_model("db", "ProjectMember")
    User = apps.get_model("db", "User")
    IssueType = apps.get_model("db", "IssueType")
    Workflow = apps.get_model("db", "Workflow")
    WorkflowTransition = apps.get_model("db", "WorkflowTransition")
    WorkflowTransitionApproval = apps.get_model("db", "WorkflowTransitionApproval")
    State = apps.get_model("db", "State")

    projects = Project.objects.filter(
        workspace__slug=TARGET_WORKSPACE_SLUG,
        deleted_at__isnull=True,
    )
    approver_users = list(
        User.objects.filter(
            display_name__in=APPROVER_DISPLAY_NAMES,
        )
    )
    if not approver_users:
        return

    for project in projects:
        _add_users_to_project(
            ProjectUserProperty, ProjectMember, approver_users, project
        )

        defect_issue_types = IssueType.objects.filter(
            project=project, deleted_at__isnull=True
        ).select_related("category")
        for defect_issue_type in defect_issue_types:
            if not _is_defect_issue_type(defect_issue_type):
                continue
            _ensure_default_reject_approvers(
                Workflow,
                WorkflowTransition,
                WorkflowTransitionApproval,
                State,
                project,
                defect_issue_type,
                approver_users,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0239_run_migrate_filestore_to_root"),
    ]

    operations = [
        migrations.RunPython(main, migrations.RunPython.noop),
    ]
