# Generated by Django 4.2.24 on 2026-05-23 07:37

from django.db import migrations
from django.utils import timezone


def remove_pending_reject_fix_version_required_field(apps, schema_editor):
    WorkflowTransition = apps.get_model("db", "WorkflowTransition")
    WorkflowTransitionRequiredField = apps.get_model("db", "WorkflowTransitionRequiredField")

    for obj in WorkflowTransition.objects.filter(to_state__name="Pending-Reject"):
        field = WorkflowTransitionRequiredField.objects.filter(workflow=obj, extra_field__name='修复版本').first()
        if field:
            field.delete()

    num = WorkflowTransition.objects.filter(from_state__name='Pending-Reject', to_state__name="Rejected").update(
        approval_type='n_of_m', required_count=2, dynamic_approver_types=["assignees", "created_by"])

class Migration(migrations.Migration):
    dependencies = [
        ("db", "0240_backfill_reject_state_approval"),
    ]

    operations = [
        migrations.RunPython(
            remove_pending_reject_fix_version_required_field,
            migrations.RunPython.noop,
        ),
    ]
