# Generated by Django 4.2.24 on 2026-05-26 03:30

from django.db import migrations, models


def migrate_release_legacy_status_to_new_status(apps, schema_editor):
    Release = apps.get_model("db", "Release")
    Release.objects.filter(status__in=["backlog", "planned", "paused"]).update(
        status="not-started"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0241_delete_pending_require_field"),
    ]

    operations = [
        migrations.RunPython(
            migrate_release_legacy_status_to_new_status,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="release",
            name="status",
            field=models.CharField(
                choices=[
                    ("not-started", "未开始"),
                    ("in-progress", "进行中"),
                    ("pending-test", "待测试"),
                    ("testing", "测试中"),
                    ("rejected", "已驳回"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="not-started",
                max_length=20,
            ),
        ),
    ]
