# Generated by Django 4.2.24 on 2026-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0242_alter_release_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='test_handoff_date',
            field=models.DateField(null=True),
        ),
    ]
