# Generated by hand on 2026-05-27

from collections import defaultdict

from django.db import migrations, transaction

import logging


logger = logging.getLogger("plane.migrations")

BATCH_SIZE = 4000


def consolidate_triage_state(apps, _schema_editor):
    """收敛 Triage state：保证每个项目仅有一条 issue_type=NULL 的 Triage。

    迁移历史背景：早期 ``bulk_create_issue_state`` 会按每个非缺陷 IssueType 各建一条
    Triage state，并以 issue_type 外键关联。IssueType 被硬删时，CASCADE 会把对应
    Triage 一并带走，导致 ``/intake-state/`` 接口长期 404。本迁移把 Triage 拍平为
    项目级单条。
    """

    Project = apps.get_model("db", "Project")
    State = apps.get_model("db", "State")
    Issue = apps.get_model("db", "Issue")

    # ------------------------------------------------------------------
    # Step 1: 确保每个项目都有一条 issue_type=NULL 的 Triage state
    # ------------------------------------------------------------------
    promoted = 0
    created = 0
    skipped = 0

    project_iter = (
        Project.objects.all()
        .values_list("id", "workspace_id")
        .iterator(chunk_size=BATCH_SIZE)
    )

    for proj_id, workspace_id in project_iter:
        has_project_level = State.objects.filter(
            project_id=proj_id,
            group="triage",
            issue_type__isnull=True,
            deleted_at__isnull=True,
        ).exists()
        if has_project_level:
            skipped += 1
            continue

        # 计算可用 name：避免和项目里已有的 (name=Triage, issue_type=NULL,
        # deleted_at IS NULL) 行撞 state_unique_name_project_when_deleted_at_null
        # 约束（沿用 0152 的命名规则）。
        name_taken = State.objects.filter(
            project_id=proj_id,
            name="Triage",
            issue_type__isnull=True,
            deleted_at__isnull=True,
        ).exists()
        target_name = "Triage" if not name_taken else f"Triage-{str(proj_id)[:5]}"

        # 优先提拔一条现有 type 级 Triage，挂在它上面的 issue 无需迁移。
        candidate = (
            State.objects.filter(
                project_id=proj_id,
                group="triage",
                issue_type__isnull=False,
                deleted_at__isnull=True,
            )
            .order_by("created_at", "id")
            .first()
        )

        if candidate is not None:
            State.objects.filter(pk=candidate.pk).update(
                name=target_name,
                issue_type=None,
            )
            promoted += 1
        else:
            State.objects.create(
                name=target_name,
                color="#4E5355",
                project_id=proj_id,
                workspace_id=workspace_id,
                sequence=65000,
                group="triage",
                default=False,
                issue_type=None,
            )
            created += 1

    logger.info(
        "Triage consolidation step 1 done: promoted=%s, created=%s, skipped=%s",
        promoted,
        created,
        skipped,
    )

    # ------------------------------------------------------------------
    # Step 2: 把仍挂在 type 级 Triage 上的 issue 重定向到项目级 Triage
    # ------------------------------------------------------------------
    project_to_target = dict(
        State.objects.filter(
            group="triage",
            issue_type__isnull=True,
            deleted_at__isnull=True,
        ).values_list("project_id", "id")
    )

    type_by_project = defaultdict(list)
    type_level_rows = State.objects.filter(
        group="triage",
        issue_type__isnull=False,
        deleted_at__isnull=True,
    ).values_list("id", "project_id")
    for type_state_id, proj_id in type_level_rows:
        type_by_project[proj_id].append(type_state_id)

    moved_total = 0
    with transaction.atomic():
        for proj_id, state_ids in type_by_project.items():
            target_id = project_to_target.get(proj_id)
            if not target_id:
                # 理论上 Step 1 已保证有项目级 Triage；防御性跳过。
                continue
            # 用 _default_manager 而非 .objects：Issue 模型显式定义了
            # issue_objects manager，Django 不会再自动注入 objects。
            moved_total += Issue._default_manager.filter(
                state_id__in=state_ids
            ).update(state_id=target_id)

    logger.info(
        "Triage consolidation step 2 done: moved %s issues to project-level triage",
        moved_total,
    )

    # ------------------------------------------------------------------
    # Step 3: 硬删活动状态下的 type 级 Triage
    # ------------------------------------------------------------------
    # 用 _base_manager 绕过任何自定义 manager，确保走默认硬删。
    deleted_count, _ = State.objects.filter(
        group="triage",
        issue_type__isnull=False,
        deleted_at__isnull=True,
    ).delete()
    logger.info(
        "Triage consolidation step 3 done: hard-deleted %s type-level triage rows",
        deleted_count,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0243_release_test_handoff_date"),
    ]

    operations = [
        migrations.RunPython(
            consolidate_triage_state,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
