# Generated by Django 4.2.24 on 2026-05-27 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0244_consolidate_triage_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseOverdueRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phase', models.CharField(choices=[('dev', '研发逾期'), ('test', '测试逾期')], max_length=8)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(choices=[('system', '系统自动'), ('user', '人工标记')], default='system', max_length=8)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overdue_records', to='db.release')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Release Overdue Record',
                'verbose_name_plural': 'Release Overdue Records',
                'db_table': 'release_overdue_records',
                'ordering': ('-started_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='releaseoverduerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('ended_at__isnull', True)), fields=('release', 'phase'), name='release_overdue_record_unique_active_per_phase'),
        ),
    ]
