# Generated by Django 4.2.24 on 2026-05-28 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0247_seed_release_comment_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='release_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='db.releasecomment'),
        ),
    ]
