# Generated by Django 4.2.24 on 2026-06-05 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0258_cycleactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasecomment',
            name='comment_html',
            field=models.TextField(blank=True, default='<p></p>'),
        ),
        migrations.AddField(
            model_name='testcasecomment',
            name='comment_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testcasecomment',
            name='comment_stripped',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testcasecomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcasecomment',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Comment Content'),
        ),
        migrations.CreateModel(
            name='TestCaseActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('verb', models.CharField(default='created', max_length=255, verbose_name='Action')),
                ('field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='New Value')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('old_identifier', models.UUIDField(blank=True, null=True)),
                ('new_identifier', models.UUIDField(blank=True, null=True)),
                ('epoch', models.FloatField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_case_activities', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='db.testcase', verbose_name='TestCase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('test_case_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_activities', to='db.testcasecomment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'TestCase Activity',
                'verbose_name_plural': 'TestCase Activities',
                'db_table': 'test_case_activities',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['case', 'created_at'], name='tc_activity_case_ts')],
            },
        ),
    ]
