# Generated by Django 4.2.24 on 2026-06-05 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0259_add_testcase_comment_richtext_and_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='test_case_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='db.testcasecomment'),
        ),
    ]
