# Generated by Django 4.2.24 on 2026-06-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0260_add_test_case_comment_description_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product_type',
            field=models.CharField(blank=True, choices=[('电表', '电表'), ('水表', '水表'), ('气表', '气表'), ('P2P', 'P2P'), ('PLC', 'PLC'), ('DCU', 'DCU'), ('CIU', 'CIU'), ('工具', '工具'), ('LoRaWAN', 'LoRaWAN'), ('RF mesh', 'RF mesh'), ('Sigfox', 'Sigfox'), ('wM-Bus', 'wM-Bus'), ('Zigbee', 'Zigbee'), ('BLE', 'BLE'), ('Gateway', 'Gateway'), ('WIFI', 'WIFI'), ('Ethernet', 'Ethernet'), ('Lora', 'Lora'), ('Hybrid', 'Hybrid'), ('WI-SUN', 'WI-SUN'), ('Repeater', 'Repeater'), ('RS485', 'RS485'), ('其他', '其他')], max_length=32, null=True, verbose_name='Project Product Type'),
        ),
    ]
