# Generated by Django 4.2.24 on 2026-06-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0262_seed_project_asset_edit_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='plan_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='db.plancase'),
        ),
        migrations.AlterField(
            model_name='filepath',
            name='entity_type',
            field=models.CharField(choices=[('WORKSPACE', 'Workspace'), ('PROJECT', 'Project'), ('FILESTORE_ROOT', 'Filestore Root'), ('USER_FOLDER', 'User Folder'), ('ISSUE', 'Issue'), ('DRAFT_ISSUE', 'Draft Issue'), ('PAGE', 'Page'), ('TESTCASE', 'Testcase'), ('CYCLE', 'Cycle'), ('RELEASE', 'Release'), ('PLAN', 'Plan'), ('PLAN_CASE', 'Plan Case'), ('PLAN_CASE_RECORD', 'Plan Case Record'), ('USER_ROOT', 'User Root'), ('USER', 'User'), ('ISSUES_CATEGORY', 'Issues Category'), ('DRAFTS_CATEGORY', 'Drafts Category'), ('PAGES_CATEGORY', 'Pages Category'), ('CYCLES_CATEGORY', 'Cycles Category'), ('RELEASES_CATEGORY', 'Releases Category'), ('PLANS_CATEGORY', 'Plans Category'), ('CASES_CATEGORY', 'Cases Category'), ('PLAN_CASE_RECORDS_CATEGORY', 'Plan Case Records Category'), ('TEMP_CATEGORY', 'Temp Category'), ('TEMP', 'Temp')], max_length=32),
        ),
    ]
