# Generated by Django 4.2.24 on 2026-06-10 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_approvers_to_principals(apps, schema_editor):
    """把旧的审批人配置迁入统一的 WorkflowTransitionPrincipal（dimension=approver）。

    - 每条 active WorkflowTransitionApproval -> kind=member 行；
    - 每个 WorkflowTransition.dynamic_approver_types 列表项 -> kind=dynamic 行。
    使用历史模型 + bulk_create，绕过应用层 clean()。
    """
    WorkflowTransition = apps.get_model("db", "WorkflowTransition")
    WorkflowTransitionApproval = apps.get_model("db", "WorkflowTransitionApproval")
    WorkflowTransitionPrincipal = apps.get_model("db", "WorkflowTransitionPrincipal")

    principals = []

    # 旧静态审批人 -> dimension=approver / kind=member
    for approval in WorkflowTransitionApproval.objects.filter(
        deleted_at__isnull=True
    ).iterator():
        principals.append(
            WorkflowTransitionPrincipal(
                transition_id=approval.transition_id,
                dimension="approver",
                kind="member",
                member_id=approval.approver_id,
            )
        )

    # 动态审批人 -> dimension=approver / kind=dynamic
    for transition in WorkflowTransition.objects.filter(
        deleted_at__isnull=True
    ).iterator():
        seen = set()
        for target in transition.dynamic_approver_types or []:
            if target in seen:
                continue
            seen.add(target)
            principals.append(
                WorkflowTransitionPrincipal(
                    transition_id=transition.id,
                    dimension="approver",
                    kind="dynamic",
                    dynamic_target=target,
                )
            )

    if principals:
        WorkflowTransitionPrincipal.objects.bulk_create(
            principals, batch_size=100, ignore_conflicts=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0265_remove_plan_case_file_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTransitionPrincipal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dimension', models.CharField(choices=[('initiator', '发起人'), ('assignee', '目标负责人'), ('approver', '审批人')], max_length=10, verbose_name='维度')),
                ('kind', models.CharField(choices=[('member', '指定成员'), ('role', '项目角色'), ('dynamic', '动态对象')], max_length=10, verbose_name='对象类型')),
                ('dynamic_target', models.CharField(blank=True, choices=[('assignees', '工作项负责人'), ('created_by', '工作项创建人')], max_length=20, null=True, verbose_name='动态对象')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transition_principals', to=settings.AUTH_USER_MODEL, verbose_name='指定成员')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transition_principals', to='db.projectrole', verbose_name='项目角色')),
            ],
            options={
                'verbose_name': 'Workflow Transition Principal',
                'verbose_name_plural': 'Workflow Transition Principals',
                'db_table': 'workflow_transition_principals',
                'ordering': ('transition', 'dimension', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='workflowtransitionprincipal',
            name='transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='db.workflowtransition', verbose_name='所属流转边'),
        ),
        migrations.AddField(
            model_name='workflowtransitionprincipal',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransitionprincipal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('dynamic_target__isnull', True), ('kind', 'member'), ('member__isnull', False), ('role__isnull', True)), models.Q(('dynamic_target__isnull', True), ('kind', 'role'), ('member__isnull', True), ('role__isnull', False)), models.Q(('dynamic_target__isnull', False), ('kind', 'dynamic'), ('member__isnull', True), ('role__isnull', True)), _connector='OR'), name='wf_principal_kind_coherent'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransitionprincipal',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('member__isnull', False)), fields=('transition', 'dimension', 'member'), name='wf_principal_uniq_member'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransitionprincipal',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('role__isnull', False)), fields=('transition', 'dimension', 'role'), name='wf_principal_uniq_role'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransitionprincipal',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('dynamic_target__isnull', False)), fields=('transition', 'dimension', 'dynamic_target'), name='wf_principal_uniq_dynamic'),
        ),
        # 表与约束就绪后，再迁移旧审批人数据；随后才删除旧字段与旧模型。
        migrations.RunPython(
            migrate_approvers_to_principals,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='workflowtransition',
            name='dynamic_approver_types',
        ),
        migrations.DeleteModel(
            name='WorkflowTransitionApproval',
        ),
    ]
