# Generated by Django 4.2.24 on 2026-06-25 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0275_fileassetversion_object_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='TestReport Name')),
                ('report_type', models.CharField(choices=[('计划报告', 'blue'), ('对外报告', 'gold')], default='计划报告', verbose_name='TestReport Type')),
                ('summary_html', models.TextField(blank=True, default='<p></p>', verbose_name='TestReport Summary HTML')),
                ('summary_json', models.JSONField(blank=True, default=dict, verbose_name='TestReport Summary JSON')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('plans', models.ManyToManyField(blank=True, db_table='test_report_plans', related_name='reports', to='db.testplan')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'TestReport',
                'verbose_name_plural': 'TestReport',
                'db_table': 'test_report',
                'ordering': ('-created_at',),
            },
        ),
    ]
