# Generated by Django 4.2.24 on 2026-07-12 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0288_product_productmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Requirement Name')),
                ('type', models.CharField(choices=[('development', '研发需求'), ('user', '用户需求')], default='development', max_length=20, verbose_name='Requirement Type')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=30, verbose_name='Requirement Priority')),
                ('description_html', models.JSONField(blank=True, null=True, verbose_name='Requirement Description HTML')),
                ('acceptance_criteria_html', models.JSONField(blank=True, null=True, verbose_name='Requirement Acceptance Criteria HTML')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requirements', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
                'db_table': 'requirements',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequirementModule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Requirement Module Name')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_modules', to='db.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Requirement Module',
                'verbose_name_plural': 'Requirement Modules',
                'db_table': 'requirement_modules',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequirementAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_attachments', to='db.fileasset', verbose_name='File Asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_attachments', to='db.requirement', verbose_name='Requirement')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Requirement Attachment',
                'verbose_name_plural': 'Requirement Attachments',
                'db_table': 'requirement_attachments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='requirements', through='db.RequirementAttachment', to='db.fileasset', verbose_name='Attachments'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='db.requirementmodule', verbose_name='Requirement Module'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_requirements', to='db.requirement', verbose_name='Parent Requirement'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='db.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='review_requirements', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddConstraint(
            model_name='requirementmodule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('product', 'name'), name='requirement_module_unique_name_product_when_not_deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementmodule',
            unique_together={('product', 'name', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='requirementattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('requirement', 'asset'), name='requirement_attachment_unique_when_not_deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementattachment',
            unique_together={('requirement', 'asset', 'deleted_at')},
        ),
    ]
