# Generated by Django 4.2.24 on 2026-07-16 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0289_remove_workspace_role_import_to_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMemberRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Workspace Member Role',
                'verbose_name_plural': 'Workspace Member Roles',
                'db_table': 'workspace_member_roles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='workspacememberinvite',
            name='custom_role_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='workspacerole',
            name='legacy_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(20, 'Admin'), (15, 'Member'), (5, 'Guest')], db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='workspacerole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('legacy_role__isnull', False)), fields=('workspace', 'legacy_role'), name='workspace_role_unique_legacy_role_when_active'),
        ),
        migrations.AddConstraint(
            model_name='workspacerole',
            constraint=models.CheckConstraint(check=models.Q(('legacy_role__isnull', True), ('legacy_role__in', [5, 15, 20]), _connector='OR'), name='workspace_role_valid_legacy_role'),
        ),
        migrations.AddField(
            model_name='workspacememberrole',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workspacememberrole',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='db.workspacemember'),
        ),
        migrations.AddField(
            model_name='workspacememberrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_member_entries', to='db.workspacerole'),
        ),
        migrations.AddField(
            model_name='workspacememberrole',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workspacememberrole',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_member_roles', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='custom_roles',
            field=models.ManyToManyField(blank=True, related_name='role_members', through='db.WorkspaceMemberRole', to='db.workspacerole'),
        ),
        migrations.AddConstraint(
            model_name='workspacememberrole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('member', 'role'), name='workspace_member_role_unique_member_role_when_active'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacememberrole',
            unique_together={('member', 'role', 'deleted_at')},
        ),
    ]
