# Generated by Django 4.2.24 on 2026-07-14 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0294_publish_requirement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementFieldTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_field_templates', to='db.product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'requirement_field_templates',
                'ordering': ('name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RequirementStructuredField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('field_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('number_range', 'Number Range'), ('boolean', 'Boolean'), ('date', 'Date'), ('select', 'Select'), ('auto_id', 'Auto ID'), ('table', 'Table')], max_length=30)),
                ('sort_key', models.DecimalField(decimal_places=18, max_digits=36)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_fields', to='db.requirementstructuredfield')),
            ],
            options={
                'db_table': 'requirement_structured_fields',
                'ordering': ('sort_key', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RequirementStructuredRevision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source_template_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('lock_version', models.PositiveIntegerField(default=1)),
                ('schema_hash', models.CharField(blank=True, default='', max_length=64)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('root_row_count', models.PositiveIntegerField(default=0)),
                ('child_row_count', models.PositiveIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requirement_structured_revisions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequirementStructuredRow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('row_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sequence_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('display_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_key', models.DecimalField(decimal_places=18, max_digits=36)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_rows', to='db.requirementstructuredrow')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='db.requirementstructuredrevision')),
                ('table_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_rows', to='db.requirementstructuredfield')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'requirement_structured_rows',
                'ordering': ('sort_key', 'created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='content_mode',
            field=models.CharField(choices=[('text', '文本'), ('structured', '结构化')], db_index=True, default='text', max_length=20, verbose_name='Requirement Content Mode'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='structured_root_row_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requirementchange',
            name='structured_diff_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='RequirementTemplateField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('field_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('number_range', 'Number Range'), ('boolean', 'Boolean'), ('date', 'Date'), ('select', 'Select'), ('auto_id', 'Auto ID'), ('table', 'Table')], max_length=30)),
                ('sort_key', models.DecimalField(decimal_places=18, max_digits=36)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_fields', to='db.requirementtemplatefield')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='db.requirementfieldtemplate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'requirement_template_fields',
                'ordering': ('sort_key', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RequirementStructuredValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_min', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('value_max', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='db.requirementstructuredfield')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='db.requirementstructuredrevision')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='db.requirementstructuredrow')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'requirement_structured_values',
            },
        ),
        migrations.AddField(
            model_name='requirementstructuredrevision',
            name='change',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_revision', to='db.requirementchange'),
        ),
        migrations.AddField(
            model_name='requirementstructuredrevision',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='requirementstructuredrevision',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_revisions', to='db.requirement'),
        ),
        migrations.AddField(
            model_name='requirementstructuredrevision',
            name='source_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_revisions', to='db.requirementstructuredrevision'),
        ),
        migrations.AddField(
            model_name='requirementstructuredrevision',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_revisions', to='db.requirementfieldtemplate'),
        ),
        migrations.AddField(
            model_name='requirementstructuredrevision',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='requirementstructuredfield',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='db.requirementstructuredrevision'),
        ),
        migrations.AddField(
            model_name='requirementstructuredfield',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.CreateModel(
            name='RequirementStructuredDiffEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scope', models.CharField(choices=[('schema', 'Schema'), ('root_row', 'Root Row'), ('child_row', 'Child Row')], max_length=20)),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('modified', 'Modified'), ('moved', 'Moved')], max_length=20)),
                ('field_key', models.UUIDField(blank=True, null=True)),
                ('row_key', models.UUIDField(blank=True, null=True)),
                ('parent_row_key', models.UUIDField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('before_value', models.JSONField(blank=True, null=True)),
                ('after_value', models.JSONField(blank=True, null=True)),
                ('sort_key', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_diff_entries', to='db.requirementchange')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'requirement_structured_diff_entries',
                'ordering': ('sort_key', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RequirementSequenceCounter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('field_key', models.UUIDField()),
                ('parent_row_key', models.UUIDField(blank=True, null=True)),
                ('next_number', models.PositiveBigIntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_counters', to='db.requirement')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'requirement_sequence_counters',
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='active_structured_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_requirements', to='db.requirementstructuredrevision', verbose_name='Active Structured Revision'),
        ),
        migrations.AddField(
            model_name='requirementversion',
            name='structured_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='db.requirementstructuredrevision', verbose_name='Structured Revision'),
        ),
        migrations.AddConstraint(
            model_name='requirementtemplatefield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('template', 'field_key'), name='requirement_template_field_unique_key'),
        ),
        migrations.AddConstraint(
            model_name='requirementtemplatefield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent_field__isnull', True)), fields=('template', 'name'), name='requirement_template_root_field_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='requirementtemplatefield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent_field__isnull', False)), fields=('template', 'parent_field', 'name'), name='requirement_template_child_field_unique_name'),
        ),
        migrations.AddIndex(
            model_name='requirementstructuredvalue',
            index=models.Index(fields=['field', 'value_number'], name='requirement_field_i_4d8ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementstructuredvalue',
            index=models.Index(fields=['field', 'value_date'], name='requirement_field_i_97379b_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirementstructuredvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('row', 'field'), name='requirement_structured_value_unique_row_field'),
        ),
        migrations.AddConstraint(
            model_name='requirementstructuredrow',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('revision', 'row_key'), name='requirement_structured_row_unique_key'),
        ),
        migrations.AddConstraint(
            model_name='requirementstructuredrow',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('parent_row__isnull', True), ('table_field__isnull', True)), models.Q(('parent_row__isnull', False), ('table_field__isnull', False)), _connector='OR'), name='requirement_structured_row_parent_table_pair'),
        ),
        migrations.AddConstraint(
            model_name='requirementstructuredfield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('revision', 'field_key'), name='requirement_structured_field_unique_key'),
        ),
        migrations.AddConstraint(
            model_name='requirementstructuredfield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent_field__isnull', True)), fields=('revision', 'name'), name='requirement_structured_root_field_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='requirementstructuredfield',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent_field__isnull', False)), fields=('revision', 'parent_field', 'name'), name='requirement_structured_child_field_unique_name'),
        ),
        migrations.AddIndex(
            model_name='requirementstructureddiffentry',
            index=models.Index(fields=['change', 'scope', 'change_type'], name='requirement_change__a8bb25_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementstructureddiffentry',
            index=models.Index(fields=['change', 'row_key'], name='requirement_change__3e63b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirementsequencecounter',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent_row_key__isnull', True)), fields=('requirement', 'field_key'), name='requirement_root_sequence_counter_unique'),
        ),
        migrations.AddConstraint(
            model_name='requirementsequencecounter',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent_row_key__isnull', False)), fields=('requirement', 'field_key', 'parent_row_key'), name='requirement_child_sequence_counter_unique'),
        ),
        migrations.AddConstraint(
            model_name='requirementfieldtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('product', 'name'), name='requirement_field_template_unique_product_name'),
        ),
    ]
