# Generated by Django 4.2.24 on 2026-07-21 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0294_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_product', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_product', to='db.product')),
            ],
            options={
                'db_table': 'product_members',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'product_roles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='productmember',
            constraint=models.UniqueConstraint(fields=('product', 'member'), name='product_member_unique'),
        ),
    ]
