# Generated by Django 4.2.24 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0295_requirement_structured_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementfieldtemplate",
            name="template_type",
            field=models.CharField(
                choices=[("structured", "Structured")],
                default="structured",
                max_length=30,
            ),
        ),
    ]
