# Generated by Django 4.2.24 on 2026-07-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0297_fix_product_description_html_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productrole',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
