# Generated by Django 4.2.24 on 2026-07-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0298_alter_productmember_id_alter_productrole_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmember",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_members",
                to="db.productrole",
            ),
        ),
    ]
