# Generated by Django 4.2.24 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


def clear_global_product_roles(apps, schema_editor):
    ProductMember = apps.get_model("db", "ProductMember")
    ProductRole = apps.get_model("db", "ProductRole")
    ProductMember.objects.update(role=None)
    ProductRole.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0299_productmember_role"),
    ]

    operations = [
        migrations.RunPython(clear_global_product_roles, migrations.RunPython.noop),
        migrations.AddField(
            model_name="productrole",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="db.product",
            ),
        ),
        migrations.AlterField(
            model_name="productrole",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="productrole",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="db.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="productrole",
            constraint=models.UniqueConstraint(
                fields=("product", "name"),
                name="product_role_unique_name_product",
            ),
        ),
    ]
