# Generated by Django 4.2.24 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


def migrate_product_member_roles(apps, schema_editor):
    ProductMember = apps.get_model("db", "ProductMember")
    ProductMemberRole = apps.get_model("db", "ProductMemberRole")

    ProductMemberRole.objects.bulk_create(
        [
            ProductMemberRole(member_id=member_id, role_id=role_id)
            for member_id, role_id in ProductMember.objects.exclude(
                role_id=None
            ).values_list("id", "role_id")
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0300_productrole_product_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMemberRole",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_roles",
                        to="db.productmember",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_member_entries",
                        to="db.productrole",
                    ),
                ),
            ],
            options={
                "db_table": "product_member_roles",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="productmember",
            name="custom_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="role_members",
                through="db.ProductMemberRole",
                to="db.productrole",
            ),
        ),
        migrations.RunPython(migrate_product_member_roles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="productmember",
            name="role",
        ),
        migrations.AddConstraint(
            model_name="productmemberrole",
            constraint=models.UniqueConstraint(
                fields=("member", "role"),
                name="product_member_role_unique_member_role",
            ),
        ),
    ]
