# Generated by Django 4.2.24 on 2026-07-22 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0301_product_member_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_template', models.BooleanField(db_index=True, default=False, verbose_name='是否为工作区模板')),
                ('title', models.CharField(max_length=255, verbose_name='需求标题')),
                ('description_html', models.TextField(blank=True, null=True, verbose_name='需求描述 HTML')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_review', '评审中'), ('published', '已发布'), ('changing', '变更中')], db_index=True, default='draft', max_length=30, verbose_name='需求状态')),
                ('approval_type', models.CharField(choices=[('any', '任一人通过'), ('all', '全部通过'), ('n_of_m', '至少 N 人通过')], default='any', max_length=10, verbose_name='审批通过规则')),
                ('required_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最少通过人数（仅 N_OF_M 模式生效）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.FloatField(default=65535, verbose_name='排序')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_requirements', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='db.product', verbose_name='所属产品')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='db.project', verbose_name='所属项目')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_copies', to='db.requirement', verbose_name='来源工作区模板')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='db.workspace', verbose_name='所属工作区')),
            ],
            options={
                'db_table': 'requirements',
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RequirementDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='明细数据')),
                ('sort_order', models.FloatField(default=65535, verbose_name='排序')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='当前版本')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='db.requirement', verbose_name='所属需求')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'requirement_details',
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RequirementField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='字段名称')),
                ('field_type', models.CharField(choices=[('text', '文本'), ('member', '成员'), ('form', '表单')], default='text', max_length=20, verbose_name='字段类型')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.FloatField(default=65535, verbose_name='排序')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='字段配置')),
                ('default_value', models.JSONField(blank=True, null=True, verbose_name='默认值')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_fields', to='db.requirementfield', verbose_name='父级表单字段')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='db.requirement', verbose_name='所属需求')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'requirement_fields',
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RequirementChangeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_kind', models.CharField(choices=[('detail_data', '明细数据'), ('schema', '字段定义')], max_length=20, verbose_name='变更目标类型')),
                ('approval_type', models.CharField(choices=[('any', '任一人通过'), ('all', '全部通过'), ('n_of_m', '至少 N 人通过')], default='any', max_length=10, verbose_name='审批通过规则快照')),
                ('required_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最少通过人数快照')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='审批状态')),
                ('reason', models.TextField(blank=True, default='', verbose_name='变更原因')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_change_requests', to='db.product', verbose_name='所属产品')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_change_requests', to='db.project', verbose_name='所属项目')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='db.requirement', verbose_name='目标需求')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_change_requests', to='db.workspace', verbose_name='所属工作区')),
            ],
            options={
                'db_table': 'requirement_change_requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequirementChangeItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('change_type', models.CharField(choices=[('create', '新增'), ('update', '更新'), ('delete', '删除')], max_length=10, verbose_name='变更类型')),
                ('target_id', models.UUIDField(blank=True, null=True, verbose_name='目标记录 ID')),
                ('before_snapshot', models.JSONField(blank=True, null=True, verbose_name='变更前快照')),
                ('proposed_snapshot', models.JSONField(blank=True, null=True, verbose_name='拟变更快照')),
                ('base_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='基准版本')),
                ('proposed_sort_order', models.FloatField(blank=True, null=True, verbose_name='拟排序值')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db.requirementchangerequest', verbose_name='所属变更请求')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'requirement_change_items',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RequirementChangeApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(blank=True, choices=[('approved', '通过'), ('rejected', '拒绝')], max_length=20, null=True, verbose_name='审批操作（null 表示尚未操作）')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_change_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='db.requirementchangerequest', verbose_name='所属变更请求')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'requirement_change_approvals',
                'ordering': ('change_request', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RequirementVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_kind', models.CharField(choices=[('detail_data', '明细数据'), ('schema', '字段定义')], max_length=20, verbose_name='版本目标类型')),
                ('target_id', models.UUIDField(verbose_name='目标记录 ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('change_type', models.CharField(choices=[('create', '新增'), ('update', '更新'), ('delete', '删除')], max_length=10, verbose_name='变更类型')),
                ('snapshot', models.JSONField(verbose_name='版本快照')),
                ('sort_order', models.FloatField(blank=True, null=True, verbose_name='排序值')),
                ('approved_by', models.JSONField(blank=True, default=list, verbose_name='审批人 ID 列表')),
                ('change_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='db.requirementchangeitem', verbose_name='来源变更项')),
                ('change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='db.requirementchangerequest', verbose_name='来源变更请求')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_versions', to='db.product', verbose_name='所属产品')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_versions', to='db.project', verbose_name='所属项目')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='db.requirement', verbose_name='所属需求')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_versions', to='db.workspace', verbose_name='所属工作区')),
            ],
            options={
                'db_table': 'requirement_versions',
                'ordering': ('-version', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_template', True), ('product__isnull', True), ('project__isnull', True)), models.Q(('is_template', False), models.Q(models.Q(('product__isnull', False), ('project__isnull', True)), models.Q(('product__isnull', True), ('project__isnull', False)), _connector='OR')), _connector='OR'), name='requirement_scope_by_template'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_template', True)), fields=('workspace', 'title'), name='requirement_unique_workspace_template_title_active'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('approval_type', 'n_of_m'), ('required_count__gte', 1)), models.Q(models.Q(('approval_type', 'n_of_m'), _negated=True), ('required_count__isnull', True)), _connector='OR'), name='requirement_required_count_consistent'),
        ),
        migrations.AddIndex(
            model_name='requirementdetail',
            index=models.Index(fields=['requirement', 'sort_order'], name='req_detail_requirement_sort'),
        ),
        migrations.AddConstraint(
            model_name='requirementchangerequest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('product__isnull', False), ('project__isnull', True)), models.Q(('product__isnull', True), ('project__isnull', False)), _connector='OR'), name='req_change_scope_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='requirementchangerequest',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('approval_type', 'n_of_m'), ('required_count__gte', 1)), models.Q(models.Q(('approval_type', 'n_of_m'), _negated=True), ('required_count__isnull', True)), _connector='OR'), name='req_change_required_count_consistent'),
        ),
        migrations.AddConstraint(
            model_name='requirementchangeapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('change_request', 'approver'), name='req_change_approval_unique_request_approver_active'),
        ),
        migrations.AddConstraint(
            model_name='requirementversion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('product__isnull', False), ('project__isnull', True)), models.Q(('product__isnull', True), ('project__isnull', False)), _connector='OR'), name='req_version_scope_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='requirementversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('target_kind', 'target_id', 'version'), name='req_version_unique_target_version_active'),
        ),
    ]
