# Generated by Django 4.2.24 on 2026-07-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0303_alter_requirementfield_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementApprover',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sort_order', models.FloatField(default=65535, verbose_name='排序')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_approvers', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='db.requirement', verbose_name='所属需求')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'requirement_approvers',
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='requirementapprover',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('requirement', 'approver'), name='req_approver_unique_requirement_approver_active'),
        ),
    ]
