# Generated by Django 4.2.24 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0306_requirement_attachment_asset_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirementfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "文本"),
                    ("member", "成员"),
                    ("select", "选择器"),
                    ("form", "表单"),
                    ("rich_text", "富文本框"),
                    ("attachment", "附件"),
                    ("image", "图片"),
                    ("boolean", "布尔值"),
                ],
                default="text",
                max_length=20,
                verbose_name="字段类型",
            ),
        ),
    ]
