# Generated by Django 4.2.24 on 2026-07-30 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0308_requirement_draft_and_change_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementLibrary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='标准库名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='标准库描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.FloatField(default=65535, verbose_name='排序')),
            ],
            options={
                'db_table': 'requirement_libraries',
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='requirementlibrary',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='requirementlibrary',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libraries', to='db.requirement', verbose_name='所选需求模板'),
        ),
        migrations.AddField(
            model_name='requirementlibrary',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='requirementlibrary',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_libraries', to='db.workspace', verbose_name='所属工作区'),
        ),
        migrations.AddConstraint(
            model_name='requirementlibrary',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='requirement_library_unique_workspace_name_active'),
        ),
        # library 列必须先建出来，作用域约束才能引用它
        migrations.AddField(
            model_name='requirement',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='db.requirementlibrary', verbose_name='所属需求标准库'),
        ),
        migrations.RemoveConstraint(
            model_name='requirement',
            name='requirement_scope_by_template',
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_template', True), ('library__isnull', True), ('product__isnull', True), ('project__isnull', True)), models.Q(('is_template', False), models.Q(models.Q(('library__isnull', False), ('product__isnull', True), ('project__isnull', True)), models.Q(('library__isnull', True), ('product__isnull', False), ('project__isnull', True)), models.Q(('library__isnull', True), ('product__isnull', True), ('project__isnull', False)), _connector='OR')), _connector='OR'), name='requirement_scope_by_template'),
        ),
    ]
