# Generated by Django 4.2.24 on 2026-08-06 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    """基线的新语义：一组 (需求, 版本) 的不可变命名快照，语义等同 git tag。

    与 0319 删掉的那个同名模型没有任何关系 —— 那个是「基线即变更单位」，持有状态与
    版本链；这个不持有状态、不参与审批，只回答「在某个时刻这批需求各自停在第几版」。
    表名复用 requirement_baselines，0319 已经把旧表删干净了。

    RequirementBaselineEntry.requirement_id 刻意是裸 UUIDField 而不是外键：需求被删掉
    之后基线仍然要能渲染，那正是打基线的意义。
    """


    dependencies = [
        ('db', '0321_requirement_schema_revision_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementBaseline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='基线名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='基线说明')),
                ('entry_count', models.PositiveIntegerField(default=0, verbose_name='收录条目数')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_baselines', to='db.product', verbose_name='所属产品')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_baselines', to='db.project', verbose_name='所属项目')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_baselines', to='db.workspace', verbose_name='所属工作区')),
            ],
            options={
                'db_table': 'requirement_baselines',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequirementBaselineEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('requirement_id', models.UUIDField(db_index=True, verbose_name='需求 ID')),
                ('sort_order', models.FloatField(default=65535, verbose_name='排序')),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='db.requirementbaseline', verbose_name='所属基线')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseline_entries', to='db.requirementversion', verbose_name='收录的版本')),
            ],
            options={
                'db_table': 'requirement_baseline_entries',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='requirementbaselineentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('baseline', 'requirement_id'), name='req_baseline_entry_unique_baseline_requirement'),
        ),
        migrations.AddConstraint(
            model_name='requirementbaseline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('product__isnull', False), ('project__isnull', True)), models.Q(('product__isnull', True), ('project__isnull', False)), _connector='OR'), name='req_baseline_scope_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='requirementbaseline',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('product__isnull', False)), fields=('product', 'name'), name='req_baseline_unique_product_name_active'),
        ),
        migrations.AddConstraint(
            model_name='requirementbaseline',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('project__isnull', False)), fields=('project', 'name'), name='req_baseline_unique_project_name_active'),
        ),
    ]
