# Generated by Django 4.2.24 on 2026-08-11 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0329_seed_project_requirement_link_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementproject',
            name='stage',
            field=models.CharField(choices=[('linked', '已立项'), ('planned', '已排期'), ('in_progress', '研发中'), ('done', '研发完毕'), ('pending_verification', '待验证'), ('released', '已发布')], db_index=True, default='linked', max_length=20, verbose_name='项目内阶段'),
        ),
        migrations.CreateModel(
            name='RequirementRelease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_requirements', to='db.release', verbose_name='关联发布')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_releases', to='db.requirement', verbose_name='关联需求')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Requirement Release',
                'verbose_name_plural': 'Requirement Releases',
                'db_table': 'requirement_releases',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequirementProjectActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('requirement_id', models.UUIDField(db_index=True, verbose_name='需求 ID')),
                ('old_stage', models.CharField(choices=[('linked', '已立项'), ('planned', '已排期'), ('in_progress', '研发中'), ('done', '研发完毕'), ('pending_verification', '待验证'), ('released', '已发布')], max_length=20, verbose_name='原阶段')),
                ('new_stage', models.CharField(choices=[('linked', '已立项'), ('planned', '已排期'), ('in_progress', '研发中'), ('done', '研发完毕'), ('pending_verification', '待验证'), ('released', '已发布')], max_length=20, verbose_name='新阶段')),
                ('trigger', models.JSONField(default=dict, verbose_name='触发来源')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Requirement Project Activity',
                'verbose_name_plural': 'Requirement Project Activities',
                'db_table': 'requirement_project_activities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequirementCycle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_requirements', to='db.cycle', verbose_name='关联迭代')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_cycles', to='db.requirement', verbose_name='关联需求')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Requirement Cycle',
                'verbose_name_plural': 'Requirement Cycles',
                'db_table': 'requirement_cycles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='requirementrelease',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('requirement', 'release'), name='requirement_release_unique_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementrelease',
            unique_together={('requirement', 'release', 'deleted_at')},
        ),
        migrations.AddIndex(
            model_name='requirementprojectactivity',
            index=models.Index(fields=['requirement_id', 'project', '-created_at'], name='req_proj_activity_lookup'),
        ),
        migrations.AddConstraint(
            model_name='requirementcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('requirement', 'cycle'), name='requirement_cycle_unique_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementcycle',
            unique_together={('requirement', 'cycle', 'deleted_at')},
        ),
    ]
