# Generated by Django 4.2.24 on 2026-08-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0331_requirement_stage_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cover_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="cover_image_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_cover_image",
                to="db.fileasset",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="logo_props",
            field=models.JSONField(default=dict),
        ),
    ]
