# Generated by Django 4.2.24 on 2026-08-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0338_requirement_issue_many_to_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaserepository',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Is Template Repository'),
        ),
    ]
