# Generated by Django 4.2.24 on 2026-08-24 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0339_testcaserepository_is_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementModule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='模块名称')),
                ('sort_order', models.FloatField(default=65535, verbose_name='排序')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='db.requirementlibrary', verbose_name='所属需求标准库')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.requirementmodule', verbose_name='父模块')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_modules', to='db.product', verbose_name='所属产品')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_modules', to='db.workspace', verbose_name='所属工作区')),
            ],
            options={
                'db_table': 'requirement_modules',
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='db.requirementmodule', verbose_name='所属需求模块'),
        ),
        migrations.AddConstraint(
            model_name='requirementmodule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('library__isnull', False), ('product__isnull', True)), models.Q(('library__isnull', True), ('product__isnull', False)), _connector='OR'), name='req_module_owner_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='requirementmodule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('library__isnull', False), ('parent__isnull', True)), fields=('library', 'name'), name='req_module_unique_library_root_name'),
        ),
        migrations.AddConstraint(
            model_name='requirementmodule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('library__isnull', False), ('parent__isnull', False)), fields=('library', 'name', 'parent'), name='req_module_unique_library_child_name'),
        ),
        migrations.AddConstraint(
            model_name='requirementmodule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True), ('product__isnull', False)), fields=('product', 'name'), name='req_module_unique_product_root_name'),
        ),
        migrations.AddConstraint(
            model_name='requirementmodule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', False), ('product__isnull', False)), fields=('product', 'name', 'parent'), name='req_module_unique_product_child_name'),
        ),
    ]
