# Generated by Django 4.2.24 on 2026-08-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0341_requirement_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requirement',
            name='req_unique_library_code_active',
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('library__isnull', False)), fields=('library', 'code'), name='req_unique_library_code_active'),
        ),
    ]
