# Generated by Django 4.2.24 on 2026-08-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0349_project_code_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="attachments",
            field=models.JSONField(blank=True, default=list, verbose_name="需求级附件"),
        ),
    ]
