# Generated by Django 4.2.24 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0352_remove_plan_case_assignee"),
    ]

    operations = [
        migrations.AddField(
            model_name="datadictionary",
            name="is_colored",
            field=models.BooleanField(default=False, verbose_name="彩色显示"),
        ),
        migrations.AddField(
            model_name="datadictionaryitem",
            name="color",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="颜色"),
        ),
    ]
