# Generated by Django 4.2.24 on 2026-09-03 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0353_data_dictionary_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='grade',
        ),
    ]
