# Generated by Django 4.2.24 on 2026-09-03

from django.db import migrations

SORT_ORDER_STEP = 10000
# 与 plane/utils/data_dictionary.py::SYSTEM_DICTIONARIES 的最后一项保持一致（迁移不能 import 运行时代码，改规格要两处同步）。
# 下标 9：排在 0346 的 6 个产品字典与 0348 的 3 个项目字典之后，与运行时 ensure_system_dictionaries 的 (index+1)*STEP 一致。
PROJECT_CODE_DICTIONARY_INDEX = 9
PROJECT_CODE_DICTIONARY = {"key": "project_code", "name": "项目代号", "description": ""}


def seed_project_code_dictionary(apps, schema_editor):
    """给存量工作区补 project_code 字典（无预置值，代号由各工作区自行维护）。

    Project.code 仍是字符串列，存量项目的代号不回填进字典：它们多是 0348 回填自 name 的占位值，
    serializer 只在代号变化时才要求命中字典。撞 key / 撞 name 的处理同 0348。
    历史模型带的是普通 Manager（看得见软删行），所以查重显式加 deleted_at__isnull=True。
    """
    Workspace = apps.get_model("db", "Workspace")
    DataDictionary = apps.get_model("db", "DataDictionary")
    spec = PROJECT_CODE_DICTIONARY

    workspace_ids = (
        Workspace.objects.filter(deleted_at__isnull=True)
        .values_list("id", flat=True)
        .iterator()
    )
    for workspace_id in workspace_ids:
        existing = DataDictionary.objects.filter(workspace_id=workspace_id, deleted_at__isnull=True)
        if existing.filter(key=spec["key"]).exists():
            continue
        name = spec["name"]
        if existing.filter(name=name).exists():
            name = f"{name}（{spec['key']}）"
            if existing.filter(name=name).exists():
                continue
        DataDictionary.objects.create(
            workspace_id=workspace_id,
            key=spec["key"],
            name=name,
            description=spec["description"],
            is_system=True,
            sort_order=(PROJECT_CODE_DICTIONARY_INDEX + 1) * SORT_ORDER_STEP,
        )


def unseed_project_code_dictionary(apps, schema_editor):
    # 只删 is_system 的这把 key，用户自建的同 key 字典不碰；items 随 CASCADE。code 是字符串列，没有 RESTRICT 要躲。
    DataDictionary = apps.get_model("db", "DataDictionary")
    DataDictionary.objects.filter(is_system=True, key=PROJECT_CODE_DICTIONARY["key"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0354_remove_project_grade"),
    ]

    operations = [
        migrations.RunPython(
            seed_project_code_dictionary, unseed_project_code_dictionary, elidable=True
        ),
    ]
