# Generated by Django 4.2.24 on 2026-09-09 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0359_seed_workspace_template_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTailoring',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='修订号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '签批中'), ('approved', '已生效'), ('rejected', '已驳回'), ('cancelled', '已取消')], db_index=True, default='draft', max_length=20, verbose_name='签批状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='裁剪 / 修订说明')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交签批时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='review_tailorings', to='db.datadictionaryitem', verbose_name='裁剪阶段')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Review Tailoring',
                'verbose_name_plural': 'Review Tailorings',
                'db_table': 'review_tailorings',
                'ordering': ('-revision', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='StageReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('review', '评审'), ('activity', '评审活动'), ('o_stage_review', 'O阶段评审'), ('o_stage_activity', 'O阶段评审活动')], db_index=True, default='review', max_length=20, verbose_name='评审类型')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description_html', models.TextField(blank=True, null=True, verbose_name='描述 HTML')),
                ('initiator_role', models.CharField(blank=True, default='', max_length=255, verbose_name='发起者角色')),
                ('leader_role', models.CharField(blank=True, default='', max_length=255, verbose_name='主导者角色')),
                ('auditor_role', models.CharField(blank=True, default='', max_length=255, verbose_name='审核者角色')),
                ('status', models.CharField(choices=[('not_started', '未评审'), ('in_review', '评审中'), ('in_approval', '审核中'), ('completed', '已评审')], db_index=True, default='not_started', max_length=20, verbose_name='状态')),
                ('result', models.CharField(blank=True, choices=[('passed', '通过'), ('rejected', '不通过'), ('waived', '免审'), ('conditional', '条件通过')], default='', max_length=20, verbose_name='评审结果')),
                ('conditional_reason', models.TextField(blank=True, default='', verbose_name='条件通过原因')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('work_instruction', models.TextField(blank=True, default='', verbose_name='工作指引')),
                ('akf_code', models.CharField(blank=True, default='', max_length=255, verbose_name='AKF 编号')),
                ('production_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='生产数量')),
                ('product_config', models.CharField(blank=True, default='', max_length=255, verbose_name='产品配置')),
                ('baseline_archive_code', models.CharField(blank=True, default='', max_length=255, verbose_name='数据基线归档编号')),
                ('components', models.JSONField(blank=True, default=list, verbose_name='组件')),
                ('component_version', models.TextField(blank=True, default='', verbose_name='组件版本 - 版本')),
                ('production_mode', models.CharField(blank=True, choices=[('normal', '正常生产'), ('risk', '风险生产')], default='', max_length=20, verbose_name='生产方式')),
                ('shipment_assessment', models.CharField(blank=True, choices=[('normal', '正常出货'), ('refresh', '出货前刷新结论'), ('risk', '风险出货')], default='', max_length=30, verbose_name='出货评估')),
                ('sort_order', models.FloatField(default=65535, verbose_name='排序')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_stage_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核者')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_stage_reviews', to=settings.AUTH_USER_MODEL, verbose_name='主导者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.stagereview', verbose_name='所属评审')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_reviews', to='db.product', verbose_name='所属产品')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stage_reviews', to='db.datadictionaryitem', verbose_name='评审阶段')),
            ],
            options={
                'verbose_name': 'Stage Review',
                'verbose_name_plural': 'Stage Reviews',
                'db_table': 'stage_reviews',
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StageReviewTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('review', '评审'), ('activity', '评审活动'), ('o_stage_review', 'O阶段评审'), ('o_stage_activity', 'O阶段评审活动')], db_index=True, default='review', max_length=20, verbose_name='类型')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description_html', models.TextField(blank=True, null=True, verbose_name='描述 HTML')),
                ('initiator_role', models.CharField(blank=True, default='', max_length=255, verbose_name='发起者角色')),
                ('leader_role', models.CharField(blank=True, default='', max_length=255, verbose_name='主导者角色')),
                ('auditor_role', models.CharField(blank=True, default='', max_length=255, verbose_name='审核者角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.FloatField(default=65535, verbose_name='排序')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.stagereviewtemplate', verbose_name='所属评审')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stage_review_templates', to='db.datadictionaryitem', verbose_name='阶段')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_review_templates', to='db.workspace', verbose_name='所属工作区')),
            ],
            options={
                'verbose_name': 'Stage Review Template',
                'verbose_name_plural': 'Stage Review Templates',
                'db_table': 'stage_review_templates',
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StageReviewComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment_html', models.TextField(blank=True, default='<p></p>')),
                ('comment_json', models.JSONField(blank=True, default=dict)),
                ('comment_stripped', models.TextField(blank=True, default='')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='编辑时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_review_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.stagereviewcomment', verbose_name='父评论')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('stage_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='db.stagereview', verbose_name='所属评审')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Stage Review Comment',
                'verbose_name_plural': 'Stage Review Comments',
                'db_table': 'stage_review_comments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='stagereview',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_reviews', to='db.stagereviewtemplate', verbose_name='来源模板项'),
        ),
        migrations.AddField(
            model_name='stagereview',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='stagereview',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.CreateModel(
            name='ReviewTailoringItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='评审标题（快照）')),
                ('selected', models.BooleanField(default=False, verbose_name='是否需要')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tailoring_items', to='db.product', verbose_name='产品')),
                ('stage_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailoring_items', to='db.stagereview', verbose_name='生成的评审')),
                ('tailoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db.reviewtailoring', verbose_name='所属裁剪单')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tailoring_items', to='db.stagereviewtemplate', verbose_name='模板评审')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Review Tailoring Item',
                'verbose_name_plural': 'Review Tailoring Items',
                'db_table': 'review_tailoring_items',
                'ordering': ('template__sort_order', 'product__name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='fileasset',
            name='stage_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='db.stagereview'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='stage_review_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='db.stagereviewcomment'),
        ),
        migrations.AddIndex(
            model_name='stagereviewtemplate',
            index=models.Index(fields=['workspace', 'stage'], name='srt_workspace_stage'),
        ),
        migrations.AddConstraint(
            model_name='stagereviewtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True)), fields=('workspace', 'stage', 'title'), name='srt_unique_stage_title_active'),
        ),
        migrations.AddConstraint(
            model_name='stagereviewtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', False)), fields=('parent', 'title'), name='srt_unique_parent_title_active'),
        ),
        migrations.AddConstraint(
            model_name='stagereviewtemplate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind__in', ('review', 'o_stage_review')), ('parent__isnull', True)), models.Q(('kind__in', ('activity', 'o_stage_activity')), ('parent__isnull', False)), _connector='OR'), name='srt_kind_parent_consistent'),
        ),
        migrations.AddIndex(
            model_name='stagereviewcomment',
            index=models.Index(fields=['stage_review', '-created_at'], name='src_review_created'),
        ),
        migrations.AddIndex(
            model_name='stagereview',
            index=models.Index(fields=['project', 'product', 'stage'], name='sr_project_product_stage'),
        ),
        migrations.AddIndex(
            model_name='stagereview',
            index=models.Index(fields=['project', 'status'], name='sr_project_status'),
        ),
        migrations.AddConstraint(
            model_name='stagereview',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind__in', ('review', 'o_stage_review')), ('parent__isnull', True)), models.Q(('kind__in', ('activity', 'o_stage_activity')), ('parent__isnull', False)), _connector='OR'), name='sr_kind_parent_consistent'),
        ),
        migrations.AddConstraint(
            model_name='stagereview',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('template__isnull', False)), fields=('project', 'product', 'template'), name='sr_unique_project_product_template_active'),
        ),
        migrations.AddIndex(
            model_name='reviewtailoringitem',
            index=models.Index(fields=['tailoring', 'product'], name='rti_tailoring_product'),
        ),
        migrations.AddConstraint(
            model_name='reviewtailoringitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tailoring', 'product', 'template'), name='rti_unique_tailoring_product_template_active'),
        ),
        migrations.AddConstraint(
            model_name='reviewtailoring',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'stage', 'revision'), name='rt_unique_project_stage_revision_active'),
        ),
        migrations.AddConstraint(
            model_name='reviewtailoring',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['draft', 'pending'])), fields=('project', 'stage'), name='rt_unique_open_per_project_stage'),
        ),
    ]
