# Generated by Django 4.2.24 on 2026-09-10 09:47

from django.conf import settings
from django.db import migrations, models


def backfill_case_level_reviewers(apps, schema_editor):
    """把评审单级的评审人回填到它下面的每一条评审用例。

    评审人下沉到用例级后，CaseReview.assignees 退化为派生汇总字段，
    存量评审单的进度与结论必须保持不变，所以这里做一次全量复制。
    """
    CaseReviewThrough = apps.get_model("db", "CaseReviewThrough")
    through_model = CaseReviewThrough.assignees.through

    review_assignees = {}
    review_through = apps.get_model("db", "CaseReview").assignees.through
    for review_id, user_id in review_through.objects.values_list("casereview_id", "user_id"):
        review_assignees.setdefault(review_id, []).append(user_id)

    if not review_assignees:
        return

    rows = []
    for crt_id, review_id in CaseReviewThrough.objects.filter(
        review_id__in=list(review_assignees.keys())
    ).values_list("id", "review_id"):
        for user_id in review_assignees[review_id]:
            rows.append(through_model(casereviewthrough_id=crt_id, user_id=user_id))

    through_model.objects.bulk_create(rows, batch_size=1000, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0359_seed_workspace_template_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereviewthrough',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_review_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_case_level_reviewers, migrations.RunPython.noop),
    ]
