# Generated by Django 4.2.24 on 2026-09-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0360_reviewtailoring_stagereview_stagereviewtemplate_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stagereview',
            name='sr_kind_parent_consistent',
        ),
        migrations.RemoveConstraint(
            model_name='stagereviewtemplate',
            name='srt_kind_parent_consistent',
        ),
        migrations.AddConstraint(
            model_name='stagereview',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind__in', ('review', 'o_stage_review')), ('parent__isnull', True)), ('kind__in', ('activity', 'o_stage_activity')), _connector='OR'), name='sr_kind_parent_consistent'),
        ),
        migrations.AddConstraint(
            model_name='stagereviewtemplate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind__in', ('review', 'o_stage_review')), ('parent__isnull', True)), ('kind__in', ('activity', 'o_stage_activity')), _connector='OR'), name='srt_kind_parent_consistent'),
        ),
    ]
