# Generated by Django 4.2.24 on 2026-09-10 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_tailoring_rows(apps, schema_editor):
    """把存量裁剪表对齐新状态机。

    三件事：补标题（新列，建表时还没有）、把已废弃的两个终态归位、让 revision 与
    approved_at 一致（旧默认值是 1，但从未生效，会撞 rt_revision_effective_consistent）。
    放在 AddConstraint 之前跑，否则约束建不上去。
    """
    ReviewTailoring = apps.get_model("db", "ReviewTailoring")
    rows = list(ReviewTailoring.objects.select_related("stage").all())
    for row in rows:
        changed = []
        if not row.title:
            label = getattr(row.stage, "label", "") or ""
            row.title = f"{label} 裁剪表".strip()
            changed.append("title")
        # rejected / cancelled 在新状态机里不存在：驳回与撤回都回到可编辑态
        if row.status in ("rejected", "cancelled"):
            row.status = "revising" if row.approved_at else "draft"
            changed.append("status")
        if row.approved_at is None and row.revision != 0:
            row.revision = 0
            changed.append("revision")
        elif row.approved_at is not None and row.revision == 0:
            row.revision = 1
            changed.append("revision")
        if changed:
            row.save(update_fields=changed)


def noop(apps, schema_editor):
    """反向不还原：rejected / cancelled 的原值无从推回，也没有还原的意义。"""


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0363_seed_review_template_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTailoringActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('verb', models.CharField(default='created', max_length=255, verbose_name='动作')),
                ('field', models.CharField(blank=True, max_length=255, null=True, verbose_name='字段名')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='新值')),
                ('comment', models.TextField(blank=True, default='', verbose_name='说明')),
                ('old_identifier', models.UUIDField(null=True)),
                ('new_identifier', models.UUIDField(null=True)),
                ('epoch', models.FloatField(null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Review Tailoring Activity',
                'verbose_name_plural': 'Review Tailoring Activities',
                'db_table': 'review_tailoring_activities',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReviewTailoringApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('round', models.PositiveIntegerField(default=1, verbose_name='第几轮签批')),
                ('action', models.CharField(blank=True, choices=[('approved', '通过'), ('rejected', '驳回')], max_length=20, null=True, verbose_name='签批动作（null 表示尚未表态）')),
                ('comment', models.TextField(blank=True, default='', verbose_name='签批意见')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='表态时间')),
            ],
            options={
                'verbose_name': 'Review Tailoring Approval',
                'verbose_name_plural': 'Review Tailoring Approvals',
                'db_table': 'review_tailoring_approvals',
                'ordering': ('tailoring', 'round', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ReviewTailoringComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment_html', models.TextField(blank=True, default='<p></p>')),
                ('comment_json', models.JSONField(blank=True, default=dict)),
                ('comment_stripped', models.TextField(blank=True, default='')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='编辑时间')),
            ],
            options={
                'verbose_name': 'Review Tailoring Comment',
                'verbose_name_plural': 'Review Tailoring Comments',
                'db_table': 'review_tailoring_comments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='reviewtailoring',
            options={'ordering': ('-created_at',), 'verbose_name': 'Review Tailoring', 'verbose_name_plural': 'Review Tailorings'},
        ),
        migrations.RemoveConstraint(
            model_name='reviewtailoring',
            name='rt_unique_project_stage_revision_active',
        ),
        migrations.RemoveConstraint(
            model_name='reviewtailoring',
            name='rt_unique_open_per_project_stage',
        ),
        migrations.RemoveConstraint(
            model_name='stagereview',
            name='sr_unique_project_product_template_active',
        ),
        migrations.RemoveField(
            model_name='reviewtailoring',
            name='remark',
        ),
        migrations.AddField(
            model_name='reviewtailoring',
            name='approval_type',
            field=models.CharField(blank=True, choices=[('any', '任一通过'), ('all', '全部通过'), ('n_of_m', '指定人数通过')], default='', max_length=10, verbose_name='签批通过规则'),
        ),
        migrations.AddField(
            model_name='reviewtailoring',
            name='description_html',
            field=models.TextField(blank=True, null=True, verbose_name='描述 HTML'),
        ),
        migrations.AddField(
            model_name='reviewtailoring',
            name='effective_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='生效快照'),
        ),
        migrations.AddField(
            model_name='reviewtailoring',
            name='required_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最少通过人数'),
        ),
        migrations.AddField(
            model_name='reviewtailoring',
            name='round',
            field=models.PositiveIntegerField(default=0, verbose_name='签批轮次'),
        ),
        migrations.AddField(
            model_name='reviewtailoring',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_review_tailorings', to=settings.AUTH_USER_MODEL, verbose_name='本轮提交人'),
        ),
        migrations.AddField(
            model_name='reviewtailoring',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewtailoringitem',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='裁剪原因'),
        ),
        migrations.AlterField(
            model_name='reviewtailoring',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近一次生效时间'),
        ),
        migrations.AlterField(
            model_name='reviewtailoring',
            name='revision',
            field=models.PositiveIntegerField(default=0, verbose_name='生效次数'),
        ),
        migrations.AlterField(
            model_name='reviewtailoring',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '签批中'), ('approved', '已生效'), ('revising', '修订中')], db_index=True, default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.RunPython(backfill_tailoring_rows, noop),
        migrations.AddIndex(
            model_name='reviewtailoring',
            index=models.Index(fields=['project', 'stage'], name='rt_project_stage'),
        ),
        migrations.AddIndex(
            model_name='reviewtailoring',
            index=models.Index(fields=['project', 'status'], name='rt_project_status'),
        ),
        migrations.AddConstraint(
            model_name='reviewtailoring',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('approval_type', 'n_of_m'), ('required_count__gte', 1)), models.Q(models.Q(('approval_type', 'n_of_m'), _negated=True), ('required_count__isnull', True)), _connector='OR'), name='rt_required_count_consistent'),
        ),
        migrations.AddConstraint(
            model_name='reviewtailoring',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('approved_at__isnull', True), ('revision', 0)), models.Q(('approved_at__isnull', False), ('revision__gte', 1)), _connector='OR'), name='rt_revision_effective_consistent'),
        ),
        migrations.AddField(
            model_name='reviewtailoringcomment',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_tailoring_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AddField(
            model_name='reviewtailoringcomment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='reviewtailoringcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.reviewtailoringcomment', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='reviewtailoringcomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='reviewtailoringcomment',
            name='tailoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='db.reviewtailoring', verbose_name='所属裁剪表'),
        ),
        migrations.AddField(
            model_name='reviewtailoringcomment',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='reviewtailoringcomment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='reviewtailoringapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tailoring_approvals', to=settings.AUTH_USER_MODEL, verbose_name='签批人'),
        ),
        migrations.AddField(
            model_name='reviewtailoringapproval',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='reviewtailoringapproval',
            name='tailoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='db.reviewtailoring', verbose_name='所属裁剪表'),
        ),
        migrations.AddField(
            model_name='reviewtailoringapproval',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='reviewtailoringactivity',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tailoring_activities', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='reviewtailoringactivity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='reviewtailoringactivity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='reviewtailoringactivity',
            name='tailoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='db.reviewtailoring', verbose_name='所属裁剪表'),
        ),
        migrations.AddField(
            model_name='reviewtailoringactivity',
            name='tailoring_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_activities', to='db.reviewtailoringcomment', verbose_name='关联评论'),
        ),
        migrations.AddField(
            model_name='reviewtailoringactivity',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='reviewtailoringactivity',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddIndex(
            model_name='reviewtailoringcomment',
            index=models.Index(fields=['tailoring', '-created_at'], name='rtc_tailoring_created'),
        ),
        migrations.AddIndex(
            model_name='reviewtailoringapproval',
            index=models.Index(fields=['tailoring', 'round'], name='rta_tailoring_round'),
        ),
        migrations.AddConstraint(
            model_name='reviewtailoringapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tailoring', 'round', 'approver'), name='rta_unique_tailoring_round_approver_active'),
        ),
        migrations.AddIndex(
            model_name='reviewtailoringactivity',
            index=models.Index(fields=['tailoring', 'created_at'], name='rtact_tailoring_created'),
        ),
    ]
