# Generated by Django 4.2.24 on 2026-09-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0360_casereviewthrough_assignees'),
        ('db', '0365_seed_review_tailoring_permissions'),
    ]

    operations = [
    ]
