# Generated by Django 4.2.24 on 2026-09-11 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0366_merge_20260911_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageReviewActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('verb', models.CharField(default='created', max_length=255, verbose_name='动作')),
                ('field', models.CharField(blank=True, max_length=255, null=True, verbose_name='字段名')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='新值')),
                ('comment', models.TextField(blank=True, default='', verbose_name='说明')),
                ('old_identifier', models.UUIDField(null=True)),
                ('new_identifier', models.UUIDField(null=True)),
                ('epoch', models.FloatField(null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_review_activities', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('stage_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='db.stagereview', verbose_name='所属评审')),
                ('stage_review_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_activities', to='db.stagereviewcomment', verbose_name='关联评论')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Stage Review Activity',
                'verbose_name_plural': 'Stage Review Activities',
                'db_table': 'stage_review_activities',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['stage_review', 'created_at'], name='sract_review_created')],
            },
        ),
    ]
