# Generated by Django 4.2.24 on 2026-09-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0376_plan_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='priority',
            field=models.IntegerField(choices=[(0, 'L'), (1, 'M'), (2, 'H')], default=1, verbose_name='TestCase Priority'),
        ),
        migrations.AlterField(
            model_name='testcaseversion',
            name='priority',
            field=models.IntegerField(choices=[(0, 'L'), (1, 'M'), (2, 'H')]),
        ),
    ]
