# Generated by Django 4.2.24 on 2026-09-22 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0384_stage_type_swap'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevMode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('icon_props', models.JSONField(blank=True, default=dict, verbose_name='图标配置')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='组件开关')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否预置')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_modes', to='db.workspace', verbose_name='所属工作区')),
            ],
            options={
                'verbose_name': 'Dev Mode',
                'verbose_name_plural': 'Dev Modes',
                'db_table': 'dev_modes',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DevModeStage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='阶段名称')),
                ('workload_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='工作量占比（%）')),
                ('standard_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='标准周期（天）')),
                ('sort_order', models.FloatField(default=65535, verbose_name='排序')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dev_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='db.devmode', verbose_name='所属研发模式')),
                ('stage_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dev_mode_stages', to='db.stagetype', verbose_name='阶段类型')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_mode_stages', to='db.workspace', verbose_name='所属工作区')),
            ],
            options={
                'verbose_name': 'Dev Mode Stage',
                'verbose_name_plural': 'Dev Mode Stages',
                'db_table': 'dev_mode_stages',
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DevModeStageTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dev_mode_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_links', to='db.devmodestage', verbose_name='所属阶段')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_mode_stage_links', to='db.stagereviewtemplate', verbose_name='评审模板节点')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Dev Mode Stage Template',
                'verbose_name_plural': 'Dev Mode Stage Templates',
                'db_table': 'dev_mode_stage_templates',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='devmodestagetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('dev_mode_stage', 'template'), name='dev_mode_stage_template_unique_active'),
        ),
        migrations.AddConstraint(
            model_name='devmodestage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('dev_mode', 'name'), name='dev_mode_stage_unique_mode_name_active'),
        ),
        migrations.AddConstraint(
            model_name='devmode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='dev_mode_unique_workspace_name_active'),
        ),
    ]
