# Generated by Django 4.2.24 on 2026-09-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0393_tailoring_kind_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='db.product', verbose_name='所属产品'),
        ),
        migrations.AddField(
            model_name='issue',
            name='product_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='db.requirementmodule', verbose_name='所属产品模块'),
        ),
    ]
