# Generated by Django 4.2.24 on 2026-03-06 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('license', '0006_instance_is_current_version_deprecated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ('-is_pinned', '-release_date', '-created_at'), 'verbose_name': 'Change Log', 'verbose_name_plural': 'Change Logs'},
        ),
        migrations.AddField(
            model_name='changelog',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='changelog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='changelog',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='changelog',
            name='links',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='changelog',
            name='screenshots',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='changelog',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='changelog',
            name='update_type',
            field=models.CharField(choices=[('added', 'Added'), ('fixed', 'Fixed'), ('improved', 'Improved')], default='improved', max_length=20),
        ),
        migrations.CreateModel(
            name='ChangeLogRead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('changelog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='license.changelog')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Change Log Read',
                'verbose_name_plural': 'Change Log Reads',
                'db_table': 'changelog_reads',
                'ordering': ('-viewed_at',),
                'unique_together': {('changelog', 'user')},
            },
        ),
    ]
