/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */

// plane imports
import type { TWorkspaceSettingsItem } from "@plane/types";
import { WORKSPACE_SETTINGS } from "../workspace";

export enum WORKSPACE_SETTINGS_CATEGORY {
  PERSONAL = "your_workspace",
  ADMINISTRATION = "administration",
  TEMPLATE = "template",
  PROJECT = "project",
  FEATURES = "features",
  DEVELOPER = "developer",
}

export const WORKSPACE_SETTINGS_CATEGORIES: WORKSPACE_SETTINGS_CATEGORY[] = [
  WORKSPACE_SETTINGS_CATEGORY.PERSONAL,
  WORKSPACE_SETTINGS_CATEGORY.ADMINISTRATION,
  WORKSPACE_SETTINGS_CATEGORY.TEMPLATE,
  WORKSPACE_SETTINGS_CATEGORY.PROJECT,
  WORKSPACE_SETTINGS_CATEGORY.FEATURES,
  WORKSPACE_SETTINGS_CATEGORY.DEVELOPER,
];

export const GROUPED_WORKSPACE_SETTINGS = {
  [WORKSPACE_SETTINGS_CATEGORY.PERSONAL]: [WORKSPACE_SETTINGS["my-access"]],
  [WORKSPACE_SETTINGS_CATEGORY.ADMINISTRATION]: [
    WORKSPACE_SETTINGS["general"],
    WORKSPACE_SETTINGS["members"],
    WORKSPACE_SETTINGS["groups"],
    WORKSPACE_SETTINGS["roles"],
    WORKSPACE_SETTINGS["export"],
  ],
  // 「模板」分区：工作项模板角色 + 需求类型
  [WORKSPACE_SETTINGS_CATEGORY.TEMPLATE]: [
    WORKSPACE_SETTINGS["templates"],
    WORKSPACE_SETTINGS["requirement-types"],
  ],
  [WORKSPACE_SETTINGS_CATEGORY.PROJECT]: [WORKSPACE_SETTINGS["issue-type-categories"]],
  [WORKSPACE_SETTINGS_CATEGORY.FEATURES]: [],
  [WORKSPACE_SETTINGS_CATEGORY.DEVELOPER]: [WORKSPACE_SETTINGS["webhooks"]],
} as Record<WORKSPACE_SETTINGS_CATEGORY, TWorkspaceSettingsItem[]>;
